ARG NODE_IMAGE=docker.io/library/node:22-bookworm
ARG JENKINS_IMAGE=docker.io/jenkins/jenkins:lts-jdk21

FROM ${NODE_IMAGE} AS node_runtime

FROM ${JENKINS_IMAGE}

USER root
COPY --from=node_runtime /usr/local/ /usr/local/

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV XDG_CACHE_HOME=/var/jenkins_home/.cache

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash ca-certificates curl git jq python3 python3-venv util-linux \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json /tmp/qa-playwright/
RUN cd /tmp/qa-playwright \
    && npm ci --registry=https://registry.npmjs.org --replace-registry-host=always \
    && npx playwright install --with-deps chromium \
    && rm -rf /tmp/qa-playwright \
    && chmod -R a+rX /ms-playwright

RUN python3 -m venv /opt/oci-cli \
    && /opt/oci-cli/bin/pip install --no-cache-dir oci-cli \
    && ln -s /opt/oci-cli/bin/oci /usr/local/bin/oci

COPY deploy/vm/jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

COPY deploy/vm/jenkins/casc.yaml /usr/share/jenkins/ref/casc.yaml
COPY deploy/vm/jenkins/jobs.groovy /usr/share/jenkins/ref/jobs.groovy
COPY deploy/vm/jenkins/entrypoint.sh /usr/local/bin/livelabs-qa-jenkins

RUN chmod 0755 /usr/local/bin/livelabs-qa-jenkins \
    && mkdir -p /var/qa-reports/par /var/qa-reports/regression \
    && chown -R jenkins:jenkins /var/qa-reports

ENTRYPOINT ["/usr/local/bin/livelabs-qa-jenkins"]