#!/usr/bin/env python3
"""Scaffold a canonical LiveStacks solution bundle."""

from __future__ import annotations

import argparse
from pathlib import Path


FILES = {
    "input/business-input.md": """# Business Input

Paste the raw user brief, workbook notes, PRD excerpts, or copied source material for this run in this file.

## Industry

## Category

## Pain Point

## Oracle Feature Mapping

## Implementation Notes

## Limitations / Risks

## Target Users

## Desired Demo Outcome

## Deployment Target

## Optional Services
""",
    "input/product-requirements.md": """# Product Requirements

## Source Mode

- Replace with `User-supplied PRD`, `Merged partial PRD`, or `No source PRD provided for this run`.

## Source Document

Replace this product requirements placeholder with the source PRD if one was provided for this run. Otherwise state that the build started from a brief and defer to `working-prd.md`.
""",
    "input/working-prd.md": """# Working PRD

This file becomes the build contract for the specialist wave. Create or update it before delegation. Every inferred item should be marked `Assumption:` until confirmed.

## Input Mode

- Replace with `PRD`, `Merge`, or `Bootstrap`.

## Source Inputs

## Program Context

Replace this working PRD placeholder with the synthesized build contract before delegation.

## Business Scenario

## Business Outcomes

## Personas

## Pain-Point Classification

## Core Workflow

## Story Architecture

## First Iteration Experience

## Oracle AI Database 26ai Protagonist Story

## Oracle 26ai Capability Strategy

oracle_26ai_primary_capability: replace-with-primary-oracle-26ai-capability
oracle_26ai_secondary_capabilities: replace-with-secondary-capabilities-or-none
why_this_oracle_feature_fits: replace-with-business-and-technical-fit

## Feature Usage Pattern

feature_usage_pattern: replace-with-semantic-matching-rag-safe-nl-to-sql-guided-agent-optimization-risk-scoring-or-other-justified-pattern

## AI Capability Mode

ai_capability_mode: replace-with-vector-rag-dbms-vector-select-ai-deterministic-nl-to-sql-local-ollama-or-documented-rejection

## Provider Boundary And Data Egress

provider_boundary: replace-with-local-oracle-local-ollama-external-provider-select-ai-profile-vector-credential-or-no-llm
data_egress_caveat: replace-with-metadata-only-local-only-retrieved-chunks-results-to-provider-or-none

## Oracle Feature Candidates

## Recommended Oracle Feature Set

## Rejected Features And Why

## Oracle Capability Mapping

## MVP Scope

## Non-Goals

## Feature Inventory

## Feature-To-Scene Mapping

evidence_surface_per_scene: replace-with-command-center-data-foundation-and-scene-evidence-map

## Dynamic Scene Architecture

Define Command Center, Data Foundation, and the right-sized set of capability-backed workflow scenes. Do not force a fixed scene count; derive `scene_count_target` from Oracle feature breadth, operator decision points, business story complexity, evidence needs, guide/demo pacing, and customer-data onboarding needs.

## Scene Experience Contract

Each scene must own a scene-specific component or page module, a distinct interaction pattern, scene-local state, visible domain objects, real Oracle evidence per scene, and workflow handoffs. Screenshot inventory captions must prove scenes are visually and behaviorally different; a repeated generic `scene-stage` shell cannot satisfy this contract.

## Oracle Internals Scene Payload

oracle_internals_scene_payload: replace-with-active-scene-route-sql-plsql-ords-ai-vector-provider-boundary-data-egress-and-security-evidence

## Data Contract

## Deployment And Runtime Assumptions

## Security And Trust Boundaries

## Redwood JET UI Quality Bar

## Non-Functional Requirements

## Acceptance Criteria

## Success Metrics

## Assumptions

## Open Questions
""",
    "input/assumptions.md": """# Assumptions

- Record only explicit assumptions made during orchestration.
- Remove assumptions that become confirmed requirements.
""",
    "input/template-provenance.json": """{
  "baseline": "capability-led-operator-application-core",
  "baseline_version": "0.1.0",
  "overlay_source": "working-prd",
  "overlay_layers": [
    "oracle_26ai_capability_strategy",
    "feature_usage_pattern",
    "industry_vocabulary",
    "pain_point_workflow",
    "dynamic_scene_architecture",
    "oracle_capability_map",
    "data_contract",
    "guide_runbook"
  ],
  "industry": "",
  "pain_point": "",
  "story_mode": "",
  "oracle_jet_redwood": true,
  "ords_first": true,
  "tailwind_allowed": false,
  "experience_pattern": "capability-led operator application",
  "notes": [
    "Generated by livestacks-orchestrator from the capability-led operator application contract.",
    "Keep stack/compose.yml and stack/.env.example aligned to the golden baseline assets.",
    "Replace empty values as soon as the working PRD is finalized.",
    "Use assets/template-overlays/industry-overlays.json as examples, not as raw templates."
  ]
}
""",
    "docs/problem-framing.md": """# Problem Framing

## Pain Point

## Users

## Business Outcomes

## Scope Boundaries
""",
    "docs/proposed-solution.md": """# Proposed Solution

## Summary

## Why Oracle Database Is The Engine

## Why This LiveStacks Shape Fits The Problem
""",
    "docs/architecture-decisions.md": """# Architecture Decisions

## Chosen Architecture

## Key Decisions

## Rejected Alternatives

## Chosen Implementation
""",
    "docs/data-design.md": """# Data Design

## Domain Model

## Oracle Feature Mapping

## ORDS Resource Plan

## Dataset Onboarding And State

## Oracle Evidence Map

## Migrations And Seed Strategy
""",
    "docs/ui-concept.md": """# UI Concept

Document the application as a capability-led operator application in premium Oracle JET / Redwood terms. Use `$redwood-creator` as the app-UI lane source of truth when it is available. The UI contract is Oracle JET framework components, Redwood theme, JET typography/font variables backed by Oracle Sans, Oracle JET icon/glyph classes for app chrome, Oracle logo/name lockup, left-side scene navigation, per-scene Oracle feature chips, Command Center, Data Foundation, dynamic capability-backed scenes, top-right masthead utility controls, scene metadata manifest, and no Tailwind.

## Personas To Screens

## Story Mode

## First Scene Interaction

## Scene Sequence

## Scene Manifest

- `stack/frontend/src/sceneManifest.js` drives scene navigation labels, guide order, screenshot names, Oracle feature chips, primary CTAs, and Oracle Internals payloads.
- Left-side scene navigation uses `oj-fwk-icon-*` glyphs and shows which Oracle features will be demonstrated by each scene.

## Dynamic Scene Architecture

## Primary CTA Path

## Screen Inventory

## Oracle Feature-To-Scene Map

## Dataset Admin Flow

## Use Your Own Data Runtime Contract

## Scene Experience Contract

- Each scene owns a scene-specific component or page module rather than sharing one repeated stage.
- Each scene has a distinct interaction pattern such as queue triage, schema lineage, ranked evidence, report runner, API workbench, architecture comparison, governed action, or dataset manager.
- Each scene carries scene-local state, visible domain objects, real Oracle evidence per scene, and workflow handoffs to the next operator step.
- Screenshot inventory captions must prove the scenes are visually and behaviorally different.

## Oracle Internals Or Database X-Ray

## Oracle AI Evidence Fields

## Redwood JET Polish Bar

- Oracle JET framework components and Redwood theme import
- Oracle JET typography/font variables backed by Oracle Sans
- Oracle JET icon/glyph classes for left-side scene navigation, titles, buttons, status, dataset actions, and Oracle Internals
- Oracle logo/name lockup on the left and a right-side collapsible scene-aware Oracle Internals rail
- Top-right masthead controls for Oracle Internals and Use Your Own Data
- No Tailwind config, `tailwindcss`, `@tailwind`, or utility-first replacement styling

## Critical Interactions

## Loading, Empty, And Error States
""",
    "docs/golden-core-overlays.md": """# Golden Core Overlays

Use this file to record how the capability-led operator application core was adapted for this run.

## Baseline

- `baseline`: `capability-led-operator-application-core`
- `baseline_version`: `0.1.0`
- `template_provenance`: `input/template-provenance.json`
- `compose_contract`: `stack/compose.yml` stays aligned to the golden baseline
- `env_contract`: `stack/.env.example` stays aligned to the golden baseline

## Oracle 26ai Capability Strategy

## Feature Usage Pattern

## Industry Vocabulary

## Pain-Point Workflow

## Dynamic Scene Architecture

## Oracle Capability Map

## Data Contract

## Guide Runbook

## Residue Review

- No wrong-industry labels remain in customer-facing UI, guide, docs, or seed examples.
- `stack/compose.yml` and `stack/.env.example` remain core-owned and do not carry domain-specific overlays.
- No Newfold-specific language remains unless Newfold is the requested industry.
- No prior-template labels remain visible unless documented as internal compatibility.
- No Tailwind, `lucide-react`, emoji iconography, or non-JET icon packs are used for app chrome.
""",
    "docs/implementation-plan.md": """# Implementation Plan

## Milestones

## Dependencies

## Critical Path

## Validation Plan

## Open Issues
""",
    "docs/feature-inventory.md": """# Feature Inventory

## Primary Workflow Features

## Operator And Admin Features

## Oracle Evidence Features

## Deferred Or Out Of Scope
""",
    "docs/oracle-capability-map.md": """# Oracle Capability Map

## Protagonist Story

## Candidate Features Considered

## Chosen Feature Set

## Feature Usage Pattern

## Rejected Features And Why

## Capability To Business Mapping

## Required Oracle Dependencies

## AI Capability Mode

## Provider Boundary And Data Egress

## Security And Data-Egress Caveats

## Scene Evidence Mapping

## Oracle Evidence Surfaces

## Customer Rebuild Implications
""",
    "docs/risks-and-review.md": """# Risks And Review

## Challenged Assumptions

## Devil's Advocate Findings

## Revisions Made

## Remaining Risks
""",
    "docs/deployment-guide.md": """# Deployment Guide

## Prerequisites

## Environment Variables

## Build And Run

## Ollama Model Bootstrap

## Health Checks
""",
    "docs/customer-rebuild.md": """# Customer Rebuild Guide

## Dataset Admin Workflow

## Dataset Package Contract

## Replace Demo Data

## Adapt Integrations

## Restore Demo Baseline

## Validate In Customer Environment
""",
    "docs/runbook.md": """# Runbook

## Startup

## Ollama Model Bootstrap

## Operational Checks

## Troubleshooting

## Recovery Notes
""",
    "stack/compose.yml": """services:
  db:
    hostname: db
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: ${ORACLE_PWD:-change-me}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/oracle/oradata/.livestack_bootstrap_done ] && echo 'SELECT 1 FROM dual;' | sqlplus -L -s system/$${ORACLE_PWD:-change-me}@localhost:1521/FREEPDB1 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 40
      start_period: 180s
    networks:
      default:
        aliases:
          - db
    volumes:
      - db-data:/opt/oracle/oradata
      - ./db:/workspace/app/db:ro,z
      - ./scripts/bootstrap_db.sh:/opt/oracle/scripts/startup/20-bootstrap_db.sh:ro,z

  ords:
    hostname: ords
    image: container-registry.oracle.com/database/ords:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONN_STRING: db:1521/${DB_SERVICE:-FREEPDB1}
      DBHOST: db
      DBPORT: 1521
      DBSERVICENAME: ${DB_SERVICE:-FREEPDB1}
      ORDS_PUBLIC_URL: ${ORDS_PUBLIC_URL:-http://127.0.0.1:8181/ords/app}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
      ORACLE_PWD: ${ORACLE_PWD:-change-me}
    ports:
      - "8181:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ords/ >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 120s
    volumes:
      - ./ords-config:/etc/ords/config:Z,U
    networks:
      default:
        aliases:
          - ords

  ollama:
    hostname: ollama
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      default:
        aliases:
          - ollama
    volumes:
      - ollama-data:/root/.ollama

  app:
    hostname: app
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      db:
        condition: service_healthy
      ords:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      APP_ENV: ${APP_ENV:-development}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-}
      PORT: 3001
      ORDS_BASE_URL: ${ORDS_BASE_URL:-http://ords:8080/ords/app}
      DB_HOST: ${DB_HOST:-db}
      DB_SERVICE: ${DB_SERVICE:-FREEPDB1}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama3.2}
      OLLAMA_EXTRA_MODELS: ${OLLAMA_EXTRA_MODELS:-gemma:2b}
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"require('http').get('http://127.0.0.1:3001/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "8505:3001"
    networks:
      default:
        aliases:
          - app

networks:
  default:

volumes:
  db-data:
  ollama-data:
""",
    "stack/Containerfile": """FROM node:20-bookworm

WORKDIR /workspace/app

COPY package.json ./
COPY frontend/package.json ./frontend/package.json
RUN npm install --include=dev \\
    && cd frontend \\
    && npm install --include=dev

COPY backend ./backend
COPY frontend ./frontend

RUN cd frontend && npm run build

EXPOSE 3001

CMD ["npm", "start"]
""",
    "stack/.env.example": """APP_ENV=development
ADMIN_TOKEN=
ORDS_BASE_URL=http://ords:8080/ords/app
ORDS_PUBLIC_URL=http://127.0.0.1:8181/ords/app
DB_HOST=db
DB_SERVICE=FREEPDB1
DB_APP_USER=app_user
DB_APP_PASSWORD=change-me
ORACLE_PWD=change-me
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_HOST_URL=http://127.0.0.1:11434
OLLAMA_MODEL=llama3.2
OLLAMA_EXTRA_MODELS=gemma:2b
OLLAMA_KEEP_ALIVE=30m
OLLAMA_WAIT_SECONDS=120
""",
    "stack/scripts/bootstrap_db.sh": """#!/bin/bash
set -euo pipefail

MARKER=/opt/oracle/oradata/.livestack_bootstrap_done
APP_ROOT=/workspace/app/db
APP_USER="${DB_APP_USER:-app_user}"
APP_PASSWORD="${DB_APP_PASSWORD:-change-me}"
ORACLE_PASSWORD="${ORACLE_PWD:-change-me}"

if [[ ! -d "$APP_ROOT" ]]; then
  echo "LiveStack database bootstrap directory is missing: $APP_ROOT" >&2
  exit 1
fi

sqlplus -L -s "system/${ORACLE_PASSWORD}@localhost:1521/FREEPDB1" <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM dba_users WHERE username = UPPER('${APP_USER}');
  IF l_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${APP_USER} IDENTIFIED BY "${APP_PASSWORD}" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER ${APP_USER} IDENTIFIED BY "${APP_PASSWORD}" ACCOUNT UNLOCK';
  END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TYPE, CREATE TRIGGER TO ${APP_USER};
GRANT CREATE JOB TO ${APP_USER};
GRANT UNLIMITED TABLESPACE TO ${APP_USER};
EXIT
SQL

for file in 001-baseline.sql 020_api_packages.sql 030_ords.sql 040_security.sql 050_demo_seed.sql; do
  if [[ -f "$APP_ROOT/$file" ]]; then
    echo "Applying $file"
    sqlplus -L -s "${APP_USER}/${APP_PASSWORD}@localhost:1521/FREEPDB1" @"$APP_ROOT/$file"
  fi
done

touch "$MARKER"
echo "LiveStack database bootstrap completed."
""",
    "stack/scripts/bootstrap_ollama_models.sh": """#!/bin/sh
set -eu

SCRIPT_DIR=$(
  CDPATH= cd -- "$(dirname -- "$0")" && pwd
)
STACK_DIR=$(
  CDPATH= cd -- "$SCRIPT_DIR/.." && pwd
)
ENV_FILE="$STACK_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

OLLAMA_HOST_URL=${OLLAMA_HOST_URL:-http://127.0.0.1:11434}
OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}
OLLAMA_EXTRA_MODELS=${OLLAMA_EXTRA_MODELS:-gemma:2b}
OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-30m}
OLLAMA_WAIT_SECONDS=${OLLAMA_WAIT_SECONDS:-120}

wait_for_ollama() {
  start_time=$(date +%s)
  while :; do
    if curl -fsS "$OLLAMA_HOST_URL/api/tags" > /dev/null 2>&1; then
      return 0
    fi
    now=$(date +%s)
    elapsed=$((now - start_time))
    if [ "$elapsed" -ge "$OLLAMA_WAIT_SECONDS" ]; then
      printf '%s\\n' "Timed out waiting for Ollama at $OLLAMA_HOST_URL" >&2
      return 1
    fi
    sleep 2
  done
}

model_stream() {
  printf '%s\\n' "$OLLAMA_MODEL"
  printf '%s\\n' "$OLLAMA_EXTRA_MODELS" | tr ',' '\\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d'
}

pull_and_warm() {
  model="$1"
  printf '%s\\n' ">>> Pulling $model"
  curl -fsS \\
    --retry 5 \\
    --retry-all-errors \\
    --retry-delay 2 \\
    "$OLLAMA_HOST_URL/api/pull" \\
    -H "Content-Type: application/json" \\
    -d "{\\"model\\":\\"$model\\",\\"stream\\":false}" > /dev/null

  printf '%s\\n' ">>> Warming $model"
  curl -fsS \\
    --retry 5 \\
    --retry-all-errors \\
    --retry-delay 2 \\
    "$OLLAMA_HOST_URL/api/generate" \\
    -H "Content-Type: application/json" \\
    -d "{\\"model\\":\\"$model\\",\\"prompt\\":\\"ping\\",\\"stream\\":false,\\"keep_alive\\":\\"$OLLAMA_KEEP_ALIVE\\"}" > /dev/null
}

printf '%s\\n' ">>> Waiting for Ollama at $OLLAMA_HOST_URL"
wait_for_ollama

model_stream | awk '!seen[$0]++' | while IFS= read -r model; do
  pull_and_warm "$model"
done

printf '%s\\n' ">>> Available models:"
curl -fsS "$OLLAMA_HOST_URL/api/tags"
""",
    "stack/scripts/bootstrap_ollama_models.ps1": """[CmdletBinding()]
param(
    [string]$OllamaHostUrl = "",
    [string]$PrimaryModel = "",
    [string]$ExtraModels = "",
    [string]$KeepAlive = "",
    [int]$WaitSeconds = 0
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$stackDir = Split-Path -Parent $scriptDir
$envFile = Join-Path $stackDir ".env"

if (Test-Path $envFile) {
    foreach ($line in Get-Content $envFile) {
        $trimmed = $line.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
            continue
        }

        $parts = $line -split "=", 2
        if ($parts.Count -ne 2) {
            continue
        }

        $name = $parts[0].Trim()
        $value = $parts[1].Trim().Trim("'`"")
        if (-not [string]::IsNullOrWhiteSpace($name) -and -not (Test-Path "Env:$name")) {
            Set-Item -Path "Env:$name" -Value $value
        }
    }
}

if ([string]::IsNullOrWhiteSpace($OllamaHostUrl)) {
    $OllamaHostUrl = $env:OLLAMA_HOST_URL
}
if ([string]::IsNullOrWhiteSpace($OllamaHostUrl)) {
    $OllamaHostUrl = "http://127.0.0.1:11434"
}
if ([string]::IsNullOrWhiteSpace($PrimaryModel)) {
    $PrimaryModel = $env:OLLAMA_MODEL
}
if ([string]::IsNullOrWhiteSpace($PrimaryModel)) {
    $PrimaryModel = "llama3.2"
}
if ([string]::IsNullOrWhiteSpace($ExtraModels)) {
    $ExtraModels = $env:OLLAMA_EXTRA_MODELS
}
if ([string]::IsNullOrWhiteSpace($ExtraModels)) {
    $ExtraModels = "gemma:2b"
}
if ([string]::IsNullOrWhiteSpace($KeepAlive)) {
    $KeepAlive = $env:OLLAMA_KEEP_ALIVE
}
if ([string]::IsNullOrWhiteSpace($KeepAlive)) {
    $KeepAlive = "30m"
}
if ($WaitSeconds -le 0) {
    $WaitSeconds = 120
    if ($env:OLLAMA_WAIT_SECONDS -match "^\\d+$") {
        $WaitSeconds = [int]$env:OLLAMA_WAIT_SECONDS
    }
}

function Wait-ForOllama {
    $deadline = (Get-Date).AddSeconds($WaitSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri "$OllamaHostUrl/api/tags" -Method Get | Out-Null
            return
        } catch {
            Start-Sleep -Seconds 2
        }
    }

    throw "Timed out waiting for Ollama at $OllamaHostUrl"
}

function Pull-And-WarmModel([string]$Model) {
    Write-Host ">>> Pulling $Model"
    $pullBody = @{ model = $Model; stream = $false } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$OllamaHostUrl/api/pull" -Method Post -ContentType "application/json" -Body $pullBody | Out-Null

    Write-Host ">>> Warming $Model"
    $warmBody = @{ model = $Model; prompt = "ping"; stream = $false; keep_alive = $KeepAlive } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$OllamaHostUrl/api/generate" -Method Post -ContentType "application/json" -Body $warmBody | Out-Null
}

$models = @($PrimaryModel)
if (-not [string]::IsNullOrWhiteSpace($ExtraModels)) {
    $models += $ExtraModels.Split(",")
}
$models = $models |
    ForEach-Object { $_.Trim() } |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Select-Object -Unique

Write-Host ">>> Waiting for Ollama at $OllamaHostUrl"
Wait-ForOllama

foreach ($model in $models) {
    Pull-And-WarmModel -Model $model
}

Write-Host ">>> Available models:"
Invoke-RestMethod -Uri "$OllamaHostUrl/api/tags" -Method Get | ConvertTo-Json -Depth 6
""",
    "stack/package.json": """{
  "name": "livestacks-app-shell",
  "private": true,
  "version": "0.1.0",
  "description": "Default LiveStacks Oracle JET / Redwood operator workbench starter.",
  "main": "backend/server.js",
  "scripts": {
    "build": "cd frontend && npm run build",
    "start": "node backend/server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.21.2",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}
""",
    "stack/backend/server.js": """require("dotenv").config();

const fs = require("fs");
const path = require("path");
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");

const app = express();
const port = Number(process.env.PORT || 3001);
const frontendDist = path.join(__dirname, "../frontend/dist");
const hasBuiltFrontend = fs.existsSync(frontendDist);
const adminToken = process.env.ADMIN_TOKEN || "";

async function fetchOrds(pathname) {
  const baseUrl = process.env.ORDS_BASE_URL;
  if (!baseUrl) {
    return {
      status: "not_configured",
      message: "ORDS_BASE_URL is not configured yet.",
    };
  }

  const response = await fetch(`${baseUrl.replace(/\\/$/, "")}${pathname}`);
  const text = await response.text();
  let payload = text;
  try {
    payload = JSON.parse(text);
  } catch {
    // Preserve text payloads from ORDS diagnostics.
  }

  return {
    status: response.ok ? "ok" : "upstream_error",
    httpStatus: response.status,
    payload,
  };
}

async function fetchOllamaTags() {
  const baseUrl = process.env.OLLAMA_BASE_URL;
  if (!baseUrl) {
    return {
      status: "not_configured",
      message: "OLLAMA_BASE_URL is not configured.",
    };
  }

  const response = await fetch(`${baseUrl.replace(/\\/$/, "")}/api/tags`);
  const text = await response.text();
  let payload = text;
  try {
    payload = JSON.parse(text);
  } catch {
    // Preserve text payloads from Ollama diagnostics.
  }

  return {
    status: response.ok ? "ok" : "upstream_error",
    httpStatus: response.status,
    payload,
  };
}

async function runtimeStatus() {
  const ordsProbe = await fetchOrds("/read/v1/health").catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));
  const ollamaProbe = await fetchOllamaTags().catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));
  const components = {
    app: {
      status: hasBuiltFrontend ? "ok" : "frontend_missing",
      frontendBuilt: hasBuiltFrontend,
    },
    ords: ordsProbe,
    ollama: ollamaProbe,
  };
  const ready =
    components.app.status === "ok" &&
    components.ords.status === "ok" &&
    components.ollama.status === "ok";

  return {
    status: ready ? "ready" : "degraded",
    appEnv: process.env.APP_ENV || "development",
    ordsBaseUrl: process.env.ORDS_BASE_URL || "",
    ollamaBaseUrl: process.env.OLLAMA_BASE_URL || "",
    ollamaModel: process.env.OLLAMA_MODEL || "llama3.2",
    ollamaExtraModels: process.env.OLLAMA_EXTRA_MODELS || "gemma:2b",
    components,
  };
}

function requireAdmin(req, res, next) {
  if (!adminToken) {
    return res.status(503).json({
      status: "admin_token_missing",
      message: "Set ADMIN_TOKEN before enabling destructive dataset operations.",
    });
  }

  const authorization = req.get("authorization") || "";
  if (authorization !== `Bearer ${adminToken}`) {
    return res.status(401).json({
      status: "unauthorized",
      message: "Destructive dataset operations require Authorization: Bearer <ADMIN_TOKEN>.",
    });
  }

  return next();
}

app.use(helmet({ contentSecurityPolicy: false }));
app.use(
  cors({
    origin: ["http://localhost:5173", "http://localhost:3000", "http://localhost:8505"],
    credentials: true,
  })
);
app.use(morgan("dev"));
app.use(express.json({ limit: "10mb" }));

app.get("/healthz", async (req, res) => {
  const status = await runtimeStatus();
  res.status(status.status === "ready" ? 200 : 503).json(status);
});

app.get("/api/health", async (req, res) => {
  const status = await runtimeStatus();
  res.status(status.status === "ready" ? 200 : 503).json(status);
});

app.get("/api/oracle/evidence", async (req, res) => {
  const ordsProbe = await fetchOrds("/read/v1/health").catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));

  res.json({
    status: "starter_contract",
    message: "Replace this starter evidence response with solution-specific ORDS routes, PL/SQL packages, SQL, and Oracle AI feature usage before calling the bundle production-ready.",
    expectedSurface: "Oracle Internals or Database X-Ray",
    ai_capability_mode: "replace-with-vector-rag-dbms-vector-select-ai-or-documented-rejection",
    provider_boundary: "replace-with-local-ollama-external-provider-select-ai-profile-vector-credential-or-no-llm",
    data_egress_caveat: "replace-with-metadata-only-local-only-retrieved-chunks-results-to-provider-or-none",
    ordsBaseUrl: process.env.ORDS_BASE_URL || "",
    ordsProbe,
    evidence: [
      {
        label: "Route contract",
        value: "app -> ORDS -> PL/SQL package APIs -> Oracle Database",
      },
      {
        label: "First scene",
        value: "Primary operator CTA should update state and refresh this Oracle evidence payload.",
      },
      {
        label: "AI evidence",
        value: "Expose embedding model, vector index, Select AI action, provider boundary, and data-egress posture when selected.",
      },
    ],
  });
});

app.get("/api/import/dataset", (req, res) => {
  res.json({
    status: "starter_contract",
    source: "demo",
    activeDatasetStateTable: "APP_DATASET_STATE",
    adminBoundary: "Authorization: Bearer <ADMIN_TOKEN>",
    message: "Wire this endpoint to Oracle-backed dataset state for the solution.",
  });
});

app.get("/api/import/template", (req, res) => {
  res.json({
    status: "starter_contract",
    format: "zip",
    message: "Wire this endpoint to a generated template archive for supported customer-data files.",
  });
});

app.post("/api/import/validate", (req, res) => {
  res.json({
    status: "starter_contract",
    mode: "validate_only",
    message: "Wire this endpoint to ORDS-backed dataset validation before destructive upload.",
  });
});

app.post("/api/import/upload", requireAdmin, (req, res) => {
  res.status(202).json({
    status: "starter_contract",
    jobId: "replace-with-oracle-job-id",
    message: "Wire this endpoint to an Oracle-backed dataset replacement job.",
  });
});

app.post("/api/import/restore-demo/validate", (req, res) => {
  res.json({
    status: "starter_contract",
    mode: "validate_restore_demo",
    message: "Wire this endpoint to validate restore-demo impact before reset.",
  });
});

app.post("/api/import/restore-demo", requireAdmin, (req, res) => {
  res.status(202).json({
    status: "starter_contract",
    jobId: "replace-with-oracle-restore-job-id",
    message: "Wire this endpoint to a restore-demo job and active dataset state update.",
  });
});

app.get("/api/import/status/:jobId", (req, res) => {
  res.json({
    status: "starter_contract",
    jobId: req.params.jobId,
    message: "Wire this endpoint to the Oracle-backed import job ledger.",
  });
});

if (hasBuiltFrontend) {
  app.use(express.static(frontendDist));
}

app.get("*", (req, res, next) => {
  if (req.path.startsWith("/api")) {
    return next();
  }

  if (!hasBuiltFrontend) {
    return res.status(503).send(
      "Frontend build not found. Run `npm run build` inside `stack/frontend` before starting the production server."
    );
  }

  return res.sendFile(path.join(frontendDist, "index.html"));
});

app.listen(port, "0.0.0.0", () => {
  console.log("LiveStack Oracle JET / Redwood operator workbench listening on port", port);
});
""",
    "stack/frontend/package.json": """{
  "name": "livestacks-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --host 0.0.0.0 --port 4173"
  },
  "dependencies": {
    "@oracle/oraclejet": "^20.0.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.4",
    "vite": "^5.4.11"
  }
}
""",
    "stack/frontend/vite.config.js": """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    host: "0.0.0.0",
    port: 5173,
  },
});
""",
    "stack/frontend/index.html": """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Capability-Led Operator Application Starter</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
    "stack/frontend/src/main.jsx": """import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "@oracle/oraclejet/dist/css/redwood/oj-redwood-notag-min.css";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
""",
    "stack/frontend/src/sceneManifest.js": """export const sceneManifest = [
  {
    id: "command-center",
    label: "Command Center",
    title: "Resolve the highest-priority operating decision",
    navIcon: "oj-fwk-icon-grid",
    guideSlug: "scene-01-command-center",
    screenshotName: "command-center.png",
    sceneType: "command-center",
    interactionPattern: "queue triage",
    evidenceObject: "ORDS decision queue",
    handoffTargets: ["capability-workflow", "operator-action"],
    oracleFeatures: ["ORDS", "PL/SQL package API", "Oracle AI Vector Search"],
    primaryAction: "Run command-center decision",
    outcome: "Command Center state changed and active-scene Oracle Internals refreshed.",
    oracleInternalsScenePayload: "ORDS route, PL/SQL package, SQL result, Oracle AI feature usage, provider boundary, data egress, and security evidence for the Command Center.",
    oracleInternals: {
      whatsHappening: "The operator action calls the app API, the app proxies ORDS, and ORDS executes a PL/SQL package that reads Oracle-owned operational state before the UI changes.",
      badges: ["ORDS REST", "PL/SQL Package API", "Oracle SQL", "Policy Guardrail"],
      sqlTitle: "Command Center read path",
      sqlSnippet: `SELECT status, COUNT(*) AS item_count
FROM livestack_operating_items
GROUP BY status
ORDER BY item_count DESC;`,
      governance: "The UI can filter and stage decisions, but Oracle constraints, package checks, and ORDS privileges own the trusted state transition.",
      flow: ["React Command Center", "Express API", "ORDS module", "PL/SQL package", "Oracle tables/views"],
    },
  },
  {
    id: "data-foundation",
    label: "Data Foundation",
    title: "Inspect the data and capability foundation",
    navIcon: "oj-fwk-icon-tree-document",
    guideSlug: "scene-02-data-foundation",
    screenshotName: "data-foundation.png",
    sceneType: "data-foundation",
    interactionPattern: "schema lineage inspector",
    evidenceObject: "APP_DATASET_STATE",
    handoffTargets: ["capability-workflow"],
    oracleFeatures: ["Dataset state", "Import contract", "Curated views"],
    primaryAction: "Verify data foundation",
    outcome: "Data Foundation verified the active dataset, import contract, and Oracle-backed capability map.",
    oracleInternalsScenePayload: "Schema objects, dataset-state table, import routes, curated views, and Oracle AI feature dependencies for the active dataset.",
    oracleInternals: {
      whatsHappening: "The scene inspects the tables, views, seed state, and import contract that make Oracle Database the system of record for the whole demo.",
      badges: ["Relational Model", "Dataset State", "Curated Views", "Import Contract"],
      sqlTitle: "Dataset state proof",
      sqlSnippet: `SELECT dataset_label,
       source_type,
       last_loaded_at
FROM app_dataset_state
FETCH FIRST 1 ROW ONLY;`,
      governance: "Demo replacement must update Oracle-backed dataset state and rebuild derived artifacts before the app reports the dataset as active.",
      flow: ["Template ZIP", "Validate route", "Oracle staging tables", "Seed/reset package", "APP_DATASET_STATE"],
    },
  },
  {
    id: "capability-workflow",
    label: "Capability Workflow",
    title: "Operate the selected Oracle 26ai feature pattern",
    navIcon: "oj-fwk-icon-database",
    guideSlug: "scene-03-capability-workflow",
    screenshotName: "capability-workflow.png",
    sceneType: "capability-workflow",
    interactionPattern: "ranked evidence workbench",
    evidenceObject: "livestack_capability_results_v",
    handoffTargets: ["operator-action"],
    oracleFeatures: ["DBMS_VECTOR", "Feature evidence", "ORDS read API"],
    primaryAction: "Run capability workflow",
    outcome: "Capability-backed workflow executed and evidence was requested from the app API.",
    oracleInternalsScenePayload: "Feature-to-scene mapping, vector or Select AI evidence, ORDS resource, and business decision output for the active scene.",
    oracleInternals: {
      whatsHappening: "This scene is where the selected Oracle 26ai capability becomes visible through a business action instead of generic dashboard copy.",
      badges: ["Oracle 26ai Capability", "Feature Evidence", "ORDS Read API", "Grounded Result"],
      sqlTitle: "Capability result query",
      sqlSnippet: `SELECT item_id,
       capability_score,
       evidence_summary
FROM livestack_capability_results_v
ORDER BY capability_score DESC
FETCH FIRST 5 ROWS ONLY;`,
      governance: "AI or automation output must stay grounded in retrieved Oracle records, scoped views, and a provider-boundary note for the active scene.",
      flow: ["Operator prompt/action", "Scoped ORDS route", "Oracle feature execution", "Evidence rows", "Grounded UI result"],
    },
  },
  {
    id: "operator-action",
    label: "Operator Action",
    title: "Publish the recommended action",
    navIcon: "oj-fwk-icon-checkmark",
    guideSlug: "scene-04-operator-action",
    screenshotName: "operator-action.png",
    sceneType: "operator-action",
    interactionPattern: "audited action publisher",
    evidenceObject: "decision audit ledger",
    handoffTargets: ["command-center", "data-foundation"],
    oracleFeatures: ["Write API", "Audit ledger", "Security policy"],
    primaryAction: "Publish operator decision",
    outcome: "Decision state staged for the domain-specific ORDS write path.",
    oracleInternalsScenePayload: "Admin boundary, write route, audit ledger, derived artifact rebuilds, and post-action readiness for the active scene.",
    oracleInternals: {
      whatsHappening: "The publish action demonstrates the write side of the contract: operator intent crosses an authorization boundary before Oracle records the decision.",
      badges: ["Write API", "Audit Ledger", "Authorization", "Derived Refresh"],
      sqlTitle: "Audited write path",
      sqlSnippet: `BEGIN
  live_stack_api.publish_decision(
    p_item_id => :item_id,
    p_decision => :decision_code
  );
END;`,
      governance: "Destructive or state-changing actions must fail closed behind ADMIN_TOKEN, Authorization, CSRF, JWT, or an equivalent operator-admin control.",
      flow: ["Operator decision", "Admin guard", "ORDS write handler", "PL/SQL transaction", "Audit ledger"],
    },
  },
];

export const datasetActions = [
  {
    eyebrow: "Template",
    title: "Download template ZIP",
    detail: "Offer the canonical import shape and identify source files versus regenerated Oracle artifacts.",
    iconClass: "oj-fwk-icon-tree-document",
  },
  {
    eyebrow: "Validate",
    title: "Preview upload before replace",
    detail: "Call the validate-only endpoint and show counts, warnings, rejects, and importability before destructive writes.",
    iconClass: "oj-fwk-icon-message-info",
  },
  {
    eyebrow: "Upload",
    title: "Run dataset replacement",
    detail: "Submit the replacement job, poll Oracle-backed job status, and refresh active dataset state.",
    iconClass: "oj-fwk-icon-arrowtail-e",
  },
  {
    eyebrow: "Restore",
    title: "Restore demo baseline",
    detail: "Provide a validate-first restore-demo path and keep the current dataset source visible.",
    iconClass: "oj-fwk-icon-clock",
  },
];
""",
    "stack/frontend/src/context/OraclePanelContext.jsx": """import { createContext, useCallback, useContext, useMemo, useState } from "react";

const OraclePanelContext = createContext(null);

export function OraclePanelProvider({ children }) {
  const [sceneEvidence, setSceneEvidence] = useState({});

  const registerSceneEvidence = useCallback((sceneId, evidence) => {
    setSceneEvidence((current) => ({
      ...current,
      [sceneId]: evidence,
    }));
  }, []);

  const value = useMemo(
    () => ({
      sceneEvidence,
      registerSceneEvidence,
    }),
    [sceneEvidence, registerSceneEvidence]
  );

  return <OraclePanelContext.Provider value={value}>{children}</OraclePanelContext.Provider>;
}

export function useOraclePanel() {
  const value = useContext(OraclePanelContext);
  if (!value) {
    throw new Error("useOraclePanel must be used inside OraclePanelProvider");
  }
  return value;
}
""",
    "stack/frontend/src/components/RegisterOraclePanel.jsx": """import { useEffect } from "react";
import { useOraclePanel } from "../context/OraclePanelContext";

export default function RegisterOraclePanel({ scene, evidence }) {
  const { registerSceneEvidence } = useOraclePanel();

  useEffect(() => {
    registerSceneEvidence(scene.id, {
      activeScene: scene.label,
      oracleFeatures: scene.oracleFeatures,
      oracleInternalsScenePayload: scene.oracleInternalsScenePayload,
      guideSlug: scene.guideSlug,
      screenshotName: scene.screenshotName,
      ...evidence,
    });
  }, [evidence, registerSceneEvidence, scene]);

  return null;
}
""",
    "stack/frontend/src/components/OracleInternalsContent.jsx": """const BADGE_PALETTE = ["red", "blue", "green", "orange", "purple", "cyan"];

function FeatureBadge({ label, color = "blue" }) {
  return <span className={`oracle-feature-badge oracle-feature-badge--${color}`}>{label}</span>;
}

function BadgeRow({ badges }) {
  return (
    <div className="oracle-internals-badges" aria-label="Oracle capability badges">
      {badges.map((badge, index) => (
        <FeatureBadge key={badge} label={badge} color={BADGE_PALETTE[index % BADGE_PALETTE.length]} />
      ))}
    </div>
  );
}

function SqlBlock({ title, code }) {
  return (
    <figure className="oracle-sql-block">
      <figcaption>{title}</figcaption>
      <pre>{code}</pre>
    </figure>
  );
}

function DiagramBox({ label, sub, index }) {
  return (
    <div className="oracle-diagram-box" style={{ "--diagram-index": index }}>
      <strong>{label}</strong>
      {sub ? <span>{sub}</span> : null}
    </div>
  );
}

function Section({ eyebrow, title, children }) {
  return (
    <section className="oracle-internals-section">
      <p className="eyebrow">{eyebrow}</p>
      <h3>{title}</h3>
      {children}
    </section>
  );
}

function GovernanceCallout({ children }) {
  return (
    <aside className="oracle-governance-callout">
      <span className="oj-fwk-icon oj-fwk-icon-message-info jet-icon" aria-hidden="true" />
      <div>
        <strong>Security / Governance</strong>
        <p>{children}</p>
      </div>
    </aside>
  );
}

function LiveEvidence({ items }) {
  return (
    <dl className="oracle-live-grid" aria-label="Live evidence">
      {items.map((item) => (
        <div key={item.label}>
          <dt>{item.label}</dt>
          <dd>{item.value || "pending"}</dd>
        </div>
      ))}
    </dl>
  );
}

const DATASET_INTERNALS = {
  whatsHappening: "The Use Your Own Data overlay is an Oracle-governed dataset workflow, not a detached upload screen. Validate, replace, restore-demo, active dataset state, and job status must all round-trip through the app API and Oracle.",
  badges: ["Dataset Governance", "Validate First", "Admin Boundary", "Oracle State"],
  sqlTitle: "Active dataset state",
  sqlSnippet: `SELECT dataset_label,
       source_type,
       status,
       last_loaded_at
FROM app_dataset_state
ORDER BY last_loaded_at DESC
FETCH FIRST 1 ROW ONLY;`,
  governance: "Upload, replace, reseed, and restore-demo routes must fail closed behind ADMIN_TOKEN, Authorization, CSRF, JWT, or an equivalent operator-admin boundary.",
  flow: ["Use Your Own Data", "Template/validate API", "Admin-gated write", "Oracle load package", "Dataset state + job status"],
};

const DEFAULT_INTERNALS = {
  whatsHappening: "This scene registers its Oracle Internals content from the active scene. Replace the starter evidence with the scene-specific route, package, SQL, governance, and live state that power the visible workflow.",
  badges: ["ORDS", "Oracle SQL", "PL/SQL Package", "Scene Evidence"],
  sqlTitle: "Scene evidence query",
  sqlSnippet: `SELECT scene_id,
       route_name,
       evidence_status
FROM livestack_scene_evidence_v
WHERE scene_id = :active_scene;`,
  governance: "The scene should name the access-control boundary, least-privilege Oracle object set, and any AI provider or data-egress caveat.",
  flow: ["Active scene", "App API", "ORDS", "Oracle package/view", "Oracle Internals evidence"],
};

function resolveInternals(activeScene, datasetOverlayOpen) {
  if (datasetOverlayOpen) {
    return DATASET_INTERNALS;
  }

  return {
    ...DEFAULT_INTERNALS,
    ...(activeScene.oracleInternals || {}),
  };
}

export default function OracleInternalsContent({
  activeScene,
  evidence,
  health,
  datasetOverlayOpen,
}) {
  const internals = resolveInternals(activeScene, datasetOverlayOpen);
  const flow = internals.flow || DEFAULT_INTERNALS.flow;

  return (
    <>
      <Section eyebrow="What's Happening" title={datasetOverlayOpen ? "Oracle owns the dataset change lifecycle" : activeScene.title}>
        <p>{internals.whatsHappening}</p>
      </Section>

      <BadgeRow badges={internals.badges || activeScene.oracleFeatures || DEFAULT_INTERNALS.badges} />

      <SqlBlock title={internals.sqlTitle || DEFAULT_INTERNALS.sqlTitle} code={internals.sqlSnippet || DEFAULT_INTERNALS.sqlSnippet} />

      <div className="oracle-diagram-grid oracle-diagram-grid--flow" aria-label="Oracle Internals data flow">
        {flow.map((item, index) => (
          <DiagramBox key={`${item}-${index}`} label={item} sub={index === 0 ? "user-facing state" : "trusted execution"} index={index} />
        ))}
      </div>

      <GovernanceCallout>{internals.governance || DEFAULT_INTERNALS.governance}</GovernanceCallout>

      <Section eyebrow="Live Evidence" title="Dynamic state from this run">
        <LiveEvidence
          items={[
            { label: "App health", value: health?.status },
            { label: "ORDS route", value: evidence?.route || "/api/oracle/evidence" },
            { label: "Active scene", value: datasetOverlayOpen ? "Use Your Own Data" : activeScene.label },
            { label: "Provider boundary", value: evidence?.providerBoundary || "record in working PRD" },
            { label: "Data egress", value: evidence?.dataEgressCaveat || "record in working PRD" },
          ]}
        />
      </Section>
    </>
  );
}
""",
    "stack/frontend/src/components/RightOraclePanel.jsx": """import { useOraclePanel } from "../context/OraclePanelContext";
import OracleInternalsContent from "./OracleInternalsContent";

export default function RightOraclePanel({ activeScene, collapsed, onToggle, health, datasetOverlayOpen }) {
  const { sceneEvidence } = useOraclePanel();
  const evidence = sceneEvidence[activeScene.id] || {};
  const title = datasetOverlayOpen ? "Use Your Own Data" : activeScene.label;

  return (
    <aside
      id="oracle-internals-panel"
      className={`right-oracle-panel ${collapsed ? "right-oracle-panel--collapsed" : ""}`}
      aria-label="Oracle Internals"
      aria-expanded={!collapsed}
    >
      <button
        className="oracle-panel-toggle"
        type="button"
        title={collapsed ? "Show Oracle Internals" : "Collapse Oracle Internals"}
        aria-expanded={!collapsed}
        aria-controls="oracle-internals-panel"
        onClick={onToggle}
      >
        <span className="oj-fwk-icon oj-fwk-icon-database jet-icon" aria-hidden="true" />
        <span>Oracle Internals</span>
      </button>

      {collapsed ? (
        <p className="oracle-panel-collapsed">Scene-aware evidence is collapsed.</p>
      ) : (
        <div className="oracle-panel-body">
          <p className="eyebrow">Oracle AI Database 26ai Internals</p>
          <h2>{title}</h2>
          <div className="feature-chip-row" aria-label="Oracle features in this scene">
            {(datasetOverlayOpen ? ["Dataset governance", "ORDS", "Admin boundary"] : activeScene.oracleFeatures).map((feature) => (
              <span className="feature-chip" key={feature}>{feature}</span>
            ))}
          </div>
          <OracleInternalsContent
            activeScene={activeScene}
            evidence={evidence}
            health={health}
            datasetOverlayOpen={datasetOverlayOpen}
          />
        </div>
      )}
    </aside>
  );
}
""",
    "stack/frontend/src/components/DatasetManagerOverlay.jsx": """import { datasetActions } from "../sceneManifest";

export default function DatasetManagerOverlay({ open, onClose, onStageAction }) {
  if (!open) {
    return null;
  }

  return (
    <div className="dataset-overlay" role="dialog" aria-modal="true" aria-labelledby="dataset-overlay-title">
      <button
        className="dataset-overlay__backdrop"
        type="button"
        aria-label="Close dataset admin overlay"
        onClick={onClose}
      />
      <section className="dataset-overlay__panel">
        <div className="dataset-overlay__header">
          <div>
            <p className="eyebrow">Operator Dataset Admin</p>
            <h2 id="dataset-overlay-title">Use Your Own Data</h2>
            <p className="dataset-overlay__lede">
              Template download, validate-only preview, upload or replace, Oracle-backed job status,
              active dataset state, and restore-demo belong in this reusable overlay.
            </p>
          </div>
          <button className="secondary-button" type="button" onClick={onClose}>
            Close
          </button>
        </div>

        <div className="dataset-overlay__grid">
          {datasetActions.map((item) => (
            <article key={item.title} className="dataset-card">
              <div className="dataset-card__header">
                <span className={`oj-fwk-icon ${item.iconClass} jet-icon`} aria-hidden="true" />
                <p className="dataset-card__eyebrow">{item.eyebrow}</p>
              </div>
              <h3>{item.title}</h3>
              <p>{item.detail}</p>
              <button className="dataset-action-button" type="button" onClick={() => onStageAction(item.title)}>
                Stage action
              </button>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
""",
    "stack/frontend/src/App.jsx": """import { useEffect, useMemo, useState } from "react";
import DatasetManagerOverlay from "./components/DatasetManagerOverlay";
import RegisterOraclePanel from "./components/RegisterOraclePanel";
import RightOraclePanel from "./components/RightOraclePanel";
import { OraclePanelProvider } from "./context/OraclePanelContext";
import { sceneManifest } from "./sceneManifest";

const fallbackStatus = {
  status: "checking",
  appEnv: "development",
  ordsBaseUrl: "",
  ollamaBaseUrl: "",
  ollamaModel: "llama3.2",
  ollamaExtraModels: "gemma:2b",
};

function RuntimeCard({ label, value, iconClass }) {
  return (
    <article className="runtime-card">
      <div className="runtime-card__header">
        <span className={`oj-fwk-icon ${iconClass} jet-icon`} aria-hidden="true" />
        <p className="runtime-label">{label}</p>
      </div>
      <p className="runtime-value">{value}</p>
    </article>
  );
}

const DECISION_ITEMS = [
  { id: "CASE-1001", label: "Highest-priority operating decision", status: "New", signal: "92 evidence score" },
  { id: "CASE-1002", label: "Escalated customer-impact item", status: "Review", signal: "7 open dependencies" },
  { id: "CASE-1003", label: "Automation recommendation pending", status: "Ready", signal: "ORDS package check" },
];

const SCHEMA_OBJECTS = [
  { id: "APP_DATASET_STATE", role: "Active dataset state", fields: ["dataset_label", "source_type", "last_loaded_at"] },
  { id: "LIVESTACK_OPERATING_ITEMS", role: "Operator queue", fields: ["item_id", "status", "priority", "owner"] },
  { id: "LIVESTACK_CAPABILITY_RESULTS_V", role: "Oracle evidence view", fields: ["item_id", "capability_score", "evidence_summary"] },
];

const CAPABILITY_RESULTS = [
  { id: "EV-01", title: "Source-backed match", score: "0.91", source: "chunk_id CHUNK-001" },
  { id: "EV-02", title: "Policy-safe recommendation", score: "0.86", source: "view LIVESTACK_CAPABILITY_RESULTS_V" },
  { id: "EV-03", title: "Related operating signal", score: "0.78", source: "ORDS /read/v1/evidence" },
];

const ACTION_OPTIONS = [
  { id: "approve", label: "Approve recommendation", control: "Authorization + audit ledger" },
  { id: "defer", label: "Defer and request more evidence", control: "Read-only evidence refresh" },
  { id: "escalate", label: "Escalate to owner", control: "PL/SQL package transaction" },
];

function SceneLead({ scene, eyebrow, children, actions }) {
  return (
    <section className="scene-lead" aria-labelledby="active-scene-heading">
      <div>
        <p className="eyebrow">{eyebrow}</p>
        <h2 id="active-scene-heading">{scene.label}</h2>
        <p>{children}</p>
        <div className="feature-chip-row" aria-label="Oracle features shown in the active scene">
          {scene.oracleFeatures.map((feature) => (
            <span className="feature-chip" key={feature}>{feature}</span>
          ))}
        </div>
      </div>
      <div className="scene-lead__actions">{actions}</div>
    </section>
  );
}

function CommandCenterScene({
  scene,
  health,
  queueFilter,
  setQueueFilter,
  selectedDecisionItem,
  setSelectedDecisionItem,
  loadSceneEvidence,
  onNavigate,
}) {
  const filteredItems = queueFilter === "All"
    ? DECISION_ITEMS
    : DECISION_ITEMS.filter((item) => item.status === queueFilter);
  const selectedItem = DECISION_ITEMS.find((item) => item.id === selectedDecisionItem) || DECISION_ITEMS[0];

  return (
    <div className="scene-body scene-body--command">
      <SceneLead
        scene={scene}
        eyebrow="Queue triage interaction pattern"
        actions={(
          <>
            <button className="primary-button" type="button" onClick={() => loadSceneEvidence(scene)}>
              <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
              <span>{scene.primaryAction}</span>
            </button>
            <button className="secondary-button" type="button" onClick={() => onNavigate("capability-workflow")}>
              <span className="oj-fwk-icon oj-fwk-icon-sortrelevancehigh jet-icon" aria-hidden="true" />
              <span>Open evidence scene</span>
            </button>
          </>
        )}
      >
        Scene-specific component: triage domain objects, change filters, select a record,
        then hand off to the Oracle capability workflow with active-scene evidence.
      </SceneLead>

      <section className="runtime-grid runtime-grid--compact" aria-label="Runtime status">
        <RuntimeCard label="APP" value={health.status || "checking"} iconClass="oj-fwk-icon-grid" />
        <RuntimeCard label="ORDS" value={health.ordsBaseUrl || "configured in env"} iconClass="oj-fwk-icon-database" />
        <RuntimeCard label="MODEL" value={health.ollamaModel || "llama3.2"} iconClass="oj-fwk-icon-message-info" />
        <RuntimeCard label="EVIDENCE" value={scene.evidenceObject} iconClass="oj-fwk-icon-view" />
      </section>

      <section className="command-workbench" data-interaction-pattern={scene.interactionPattern}>
        <div className="queue-filter" aria-label="Queue filters">
          {["All", "New", "Review", "Ready"].map((status) => (
            <button
              key={status}
              className={queueFilter === status ? "chip-button chip-button--active" : "chip-button"}
              type="button"
              onClick={() => setQueueFilter(status)}
            >
              {status}
            </button>
          ))}
        </div>

        <div className="decision-queue">
          {filteredItems.map((item) => (
            <button
              key={item.id}
              className={selectedItem.id === item.id ? "domain-object-card domain-object-card--active" : "domain-object-card"}
              type="button"
              onClick={() => setSelectedDecisionItem(item.id)}
            >
              <span>{item.status}</span>
              <strong>{item.label}</strong>
              <small>{item.id} / {item.signal}</small>
            </button>
          ))}
        </div>

        <article className="decision-panel">
          <p className="eyebrow">Selected domain object</p>
          <h3>{selectedItem.label}</h3>
          <p>{selectedItem.id} uses scene-local selected-record state and hands off to {scene.handoffTargets.join(", ")}.</p>
          <button className="secondary-button" type="button" onClick={() => onNavigate("operator-action")}>
            <span className="oj-fwk-icon oj-fwk-icon-checkmark jet-icon" aria-hidden="true" />
            <span>Handoff to operator action</span>
          </button>
        </article>
      </section>
    </div>
  );
}

function DataFoundationScene({ scene, selectedSchemaObject, setSelectedSchemaObject, loadSceneEvidence, onNavigate }) {
  const selectedObject = SCHEMA_OBJECTS.find((object) => object.id === selectedSchemaObject) || SCHEMA_OBJECTS[0];

  return (
    <div className="scene-body scene-body--foundation">
      <SceneLead
        scene={scene}
        eyebrow="Schema lineage interaction pattern"
        actions={(
          <button className="primary-button" type="button" onClick={() => loadSceneEvidence(scene)}>
            <span className="oj-fwk-icon oj-fwk-icon-database jet-icon" aria-hidden="true" />
            <span>{scene.primaryAction}</span>
          </button>
        )}
      >
        Scene-specific component: inspect Oracle objects, fields, lineage, and dataset state
        before moving into capability execution.
      </SceneLead>

      <section className="foundation-workbench" data-interaction-pattern={scene.interactionPattern}>
        <div className="schema-map">
          {SCHEMA_OBJECTS.map((object) => (
            <button
              key={object.id}
              className={selectedObject.id === object.id ? "schema-node schema-node--active" : "schema-node"}
              type="button"
              onClick={() => setSelectedSchemaObject(object.id)}
            >
              <span className="oj-fwk-icon oj-fwk-icon-folderhierarchy jet-icon" aria-hidden="true" />
              <strong>{object.id}</strong>
              <small>{object.role}</small>
            </button>
          ))}
        </div>

        <article className="schema-detail">
          <p className="eyebrow">Selected Oracle object</p>
          <h3>{selectedObject.id}</h3>
          <p>{selectedObject.role} proves the Oracle system-of-record and import-contract foundation.</p>
          <div className="field-chip-row">
            {selectedObject.fields.map((field) => <span key={field}>{field}</span>)}
          </div>
          <button className="secondary-button" type="button" onClick={() => onNavigate("capability-workflow")}>
            <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
            <span>Handoff to capability workflow</span>
          </button>
        </article>

        <article className="lineage-panel">
          <p className="eyebrow">Data flow</p>
          <ol>
            <li>Template or seed data enters Oracle staging.</li>
            <li>PL/SQL validation updates dataset state.</li>
            <li>Curated views expose trusted records to ORDS.</li>
            <li>Scene evidence uses the same Oracle objects.</li>
          </ol>
        </article>
      </section>
    </div>
  );
}

function CapabilityWorkflowScene({ scene, selectedEvidenceId, setSelectedEvidenceId, loadSceneEvidence, onNavigate }) {
  const selectedEvidence = CAPABILITY_RESULTS.find((result) => result.id === selectedEvidenceId) || CAPABILITY_RESULTS[0];

  return (
    <div className="scene-body scene-body--capability">
      <SceneLead
        scene={scene}
        eyebrow="Ranked evidence interaction pattern"
        actions={(
          <button className="primary-button" type="button" onClick={() => loadSceneEvidence(scene)}>
            <span className="oj-fwk-icon oj-fwk-icon-sortrelevancehigh jet-icon" aria-hidden="true" />
            <span>{scene.primaryAction}</span>
          </button>
        )}
      >
        Scene-specific component: run the selected Oracle 26ai capability, inspect ranked
        evidence, and keep source attribution visible before action.
      </SceneLead>

      <section className="capability-workbench" data-interaction-pattern={scene.interactionPattern}>
        <div className="evidence-results">
          {CAPABILITY_RESULTS.map((result) => (
            <button
              key={result.id}
              className={selectedEvidence.id === result.id ? "evidence-result evidence-result--active" : "evidence-result"}
              type="button"
              onClick={() => setSelectedEvidenceId(result.id)}
            >
              <span>{result.score}</span>
              <strong>{result.title}</strong>
              <small>{result.source}</small>
            </button>
          ))}
        </div>

        <article className="evidence-detail">
          <p className="eyebrow">Real Oracle evidence per scene</p>
          <h3>{selectedEvidence.title}</h3>
          <p>{selectedEvidence.source} / {scene.evidenceObject}</p>
          <button className="secondary-button" type="button" onClick={() => onNavigate("operator-action")}>
            <span className="oj-fwk-icon oj-fwk-icon-checkmark jet-icon" aria-hidden="true" />
            <span>Use this evidence</span>
          </button>
        </article>
      </section>
    </div>
  );
}

function OperatorActionScene({ scene, selectedAction, setSelectedAction, loadSceneEvidence, onNavigate }) {
  const activeAction = ACTION_OPTIONS.find((option) => option.id === selectedAction) || ACTION_OPTIONS[0];

  return (
    <div className="scene-body scene-body--action">
      <SceneLead
        scene={scene}
        eyebrow="Audited action interaction pattern"
        actions={(
          <button className="primary-button" type="button" onClick={() => loadSceneEvidence(scene)}>
            <span className="oj-fwk-icon oj-fwk-icon-checkmark jet-icon" aria-hidden="true" />
            <span>{scene.primaryAction}</span>
          </button>
        )}
      >
        Scene-specific component: choose an operator action, review the governance control,
        and return to the Command Center after Oracle records audit evidence.
      </SceneLead>

      <section className="operator-action-workbench" data-interaction-pattern={scene.interactionPattern}>
        <div className="action-selector">
          {ACTION_OPTIONS.map((option) => (
            <button
              key={option.id}
              className={activeAction.id === option.id ? "action-option action-option--active" : "action-option"}
              type="button"
              onClick={() => setSelectedAction(option.id)}
            >
              <strong>{option.label}</strong>
              <small>{option.control}</small>
            </button>
          ))}
        </div>

        <article className="action-review-panel">
          <p className="eyebrow">Governed decision</p>
          <h3>{activeAction.label}</h3>
          <p>{activeAction.control} produces evidence object: {scene.evidenceObject}.</p>
          <button className="secondary-button" type="button" onClick={() => onNavigate("command-center")}>
            <span className="oj-fwk-icon oj-fwk-icon-grid jet-icon" aria-hidden="true" />
            <span>Return to Command Center</span>
          </button>
        </article>
      </section>
    </div>
  );
}

function ActivityStrip({ actionLog }) {
  return (
    <section className="activity-strip">
      <article>
        <p className="eyebrow">Scene Experience Contract</p>
        <strong>Distinct scene components</strong>
        <span>Components, interaction patterns, state, domain objects, evidence, and handoffs vary by scene.</span>
      </article>
      <article className="action-log" aria-live="polite">
        <p className="eyebrow">Action log</p>
        <ul>
          {actionLog.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      </article>
    </section>
  );
}

function AppShell() {
  const [health, setHealth] = useState(fallbackStatus);
  const [activeSceneId, setActiveSceneId] = useState(sceneManifest[0].id);
  const [datasetOverlayOpen, setDatasetOverlayOpen] = useState(false);
  const [oraclePanelCollapsed, setOraclePanelCollapsed] = useState(false);
  const [actionLog, setActionLog] = useState(["Command Center opened on the first operator decision."]);
  const [queueFilter, setQueueFilter] = useState("All");
  const [selectedDecisionItem, setSelectedDecisionItem] = useState("CASE-1001");
  const [selectedSchemaObject, setSelectedSchemaObject] = useState("APP_DATASET_STATE");
  const [selectedEvidenceId, setSelectedEvidenceId] = useState("EV-01");
  const [selectedAction, setSelectedAction] = useState("approve");
  const [evidence, setEvidence] = useState({
    status: "pending",
    route: "/api/oracle/evidence",
    aiCapabilityMode: "pending",
    providerBoundary: "pending",
    dataEgressCaveat: "pending",
  });

  const activeScene = useMemo(
    () => sceneManifest.find((scene) => scene.id === activeSceneId) || sceneManifest[0],
    [activeSceneId]
  );

  useEffect(() => {
    let active = true;

    fetch("/api/health")
      .then((response) => response.json())
      .then((payload) => {
        if (active) {
          setHealth(payload);
        }
      })
      .catch(() => {
        if (active) {
          setHealth((current) => ({ ...current, status: "offline" }));
        }
      });

    return () => {
      active = false;
    };
  }, []);

  async function loadSceneEvidence(scene = activeScene) {
    const stamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    setActionLog((items) => [`${stamp} - ${scene.outcome}`, ...items].slice(0, 5));

    try {
      const response = await fetch(`/api/oracle/evidence?scene=${scene.id}`);
      const payload = await response.json();
      setEvidence({
        status: payload.status || "ok",
        route: "/api/oracle/evidence",
        expectedSurface: payload.expectedSurface || "Oracle Internals",
        oracleInternalsScenePayload: scene.oracleInternalsScenePayload,
        aiCapabilityMode: payload.ai_capability_mode || "replace with solution-specific AI mode",
        providerBoundary: payload.provider_boundary || "replace with provider boundary",
        dataEgressCaveat: payload.data_egress_caveat || "replace with data-egress caveat",
      });
    } catch {
      setEvidence({
        status: "offline",
        route: "/api/oracle/evidence",
        oracleInternalsScenePayload: scene.oracleInternalsScenePayload,
        aiCapabilityMode: "unavailable",
        providerBoundary: "unavailable",
        dataEgressCaveat: "unavailable",
      });
    }
  }

  function goToScene(sceneId) {
    const nextScene = sceneManifest.find((scene) => scene.id === sceneId);
    setActiveSceneId(sceneId);
    if (nextScene) {
      const stamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      setActionLog((items) => [`${stamp} - Handoff opened ${nextScene.label}.`, ...items].slice(0, 5));
    }
  }

  function renderScene() {
    if (activeScene.id === "data-foundation") {
      return (
        <DataFoundationScene
          scene={activeScene}
          selectedSchemaObject={selectedSchemaObject}
          setSelectedSchemaObject={setSelectedSchemaObject}
          loadSceneEvidence={loadSceneEvidence}
          onNavigate={goToScene}
        />
      );
    }

    if (activeScene.id === "capability-workflow") {
      return (
        <CapabilityWorkflowScene
          scene={activeScene}
          selectedEvidenceId={selectedEvidenceId}
          setSelectedEvidenceId={setSelectedEvidenceId}
          loadSceneEvidence={loadSceneEvidence}
          onNavigate={goToScene}
        />
      );
    }

    if (activeScene.id === "operator-action") {
      return (
        <OperatorActionScene
          scene={activeScene}
          selectedAction={selectedAction}
          setSelectedAction={setSelectedAction}
          loadSceneEvidence={loadSceneEvidence}
          onNavigate={goToScene}
        />
      );
    }

    return (
      <CommandCenterScene
        scene={activeScene}
        health={health}
        queueFilter={queueFilter}
        setQueueFilter={setQueueFilter}
        selectedDecisionItem={selectedDecisionItem}
        setSelectedDecisionItem={setSelectedDecisionItem}
        loadSceneEvidence={loadSceneEvidence}
        onNavigate={goToScene}
      />
    );
  }

  function stageDatasetAction(title) {
    const stamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    setActionLog((items) => [`${stamp} - Dataset action staged: ${title}`, ...items].slice(0, 5));
  }

  return (
    <main className="app-shell">
      <RegisterOraclePanel scene={activeScene} evidence={evidence} />

      <aside className="left-oracle-rail">
        <div className="app-brand-lockup" aria-label="Oracle LiveStack">
          <div className="oracle-logo-mark">ORACLE</div>
          <div>
            <p>LiveStack</p>
            <strong>Capability Workbench</strong>
          </div>
        </div>

        <nav className="scene-rail" aria-label="Scene navigation">
          {sceneManifest.map((scene) => (
            <button
              key={scene.id}
              className="scene-nav-item"
              type="button"
              aria-current={scene.id === activeScene.id ? "page" : undefined}
              onClick={() => goToScene(scene.id)}
            >
              <span className={`oj-fwk-icon ${scene.navIcon} scene-nav-icon`} aria-hidden="true" />
              <span className="scene-nav-copy">
                <span className="scene-nav-label">{scene.label}</span>
                <span className="scene-nav-features">
                  {scene.oracleFeatures.slice(0, 2).map((feature) => (
                    <span className="feature-chip feature-chip--rail" key={feature}>{feature}</span>
                  ))}
                </span>
              </span>
            </button>
          ))}
        </nav>
      </aside>

      <section className="work-area">
        <header className="topbar">
          <div>
            <p className="eyebrow">Oracle JET Redwood Capability-Led Operator Application</p>
            <h1>{activeScene.title}</h1>
          </div>
          <div className="topbar-actions" aria-label="Application utilities">
            <button
              className="utility-button"
              type="button"
              aria-expanded={!oraclePanelCollapsed}
              aria-controls="oracle-internals-panel"
              onClick={() => setOraclePanelCollapsed((value) => !value)}
            >
              <span className="oj-fwk-icon oj-fwk-icon-database jet-icon" aria-hidden="true" />
              <span>Oracle Internals</span>
            </button>
            <button
              className="utility-button utility-button--primary"
              type="button"
              onClick={() => setDatasetOverlayOpen(true)}
            >
              <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
              <span>Use Your Own Data</span>
            </button>
          </div>
        </header>

        {renderScene()}

        <ActivityStrip actionLog={actionLog} />
      </section>

      <RightOraclePanel
        activeScene={activeScene}
        collapsed={oraclePanelCollapsed}
        onToggle={() => setOraclePanelCollapsed((value) => !value)}
        health={health}
        datasetOverlayOpen={datasetOverlayOpen}
      />

      <DatasetManagerOverlay
        open={datasetOverlayOpen}
        onClose={() => setDatasetOverlayOpen(false)}
        onStageAction={stageDatasetAction}
      />
    </main>
  );
}

export default function App() {
  return (
    <OraclePanelProvider>
      <AppShell />
    </OraclePanelProvider>
  );
}
""",
    "stack/frontend/src/styles.css": """:root {
  color-scheme: light;
  --oracle-red: #c74634;
  --oracle-bark: #312d2a;
  --surface: var(--oj-core-bg-color-content, #ffffff);
  --surface-alt: rgb(var(--oj-palette-neutral-rgb-10, 244 242 240));
  --page-bg: rgb(var(--oj-palette-neutral-rgb-20, 235 232 229));
  --line: var(--oj-core-divider-color, rgba(49, 45, 42, 0.14));
  --text-main: var(--oj-core-text-color-primary, #161513);
  --text-muted: var(--oj-core-text-color-secondary, #4f4a46);
  --shadow-sm: 0 8px 20px rgba(22, 21, 19, 0.06);
  font-family: var(--oj-html-font-family, "Oracle Sans", "Segoe UI", sans-serif);
  color: var(--text-main);
}

* {
  box-sizing: border-box;
}

html,
body,
#root {
  margin: 0;
  min-height: 100vh;
}

body {
  background: var(--page-bg);
  color: var(--text-main);
  /* Oracle JET Redwood theme supplies --oj-html-font-family; Oracle Sans remains the required fallback. */
  font-family: var(--oj-html-font-family, "Oracle Sans", "Segoe UI", sans-serif);
}

button {
  font: inherit;
}

.app-shell {
  min-height: 100vh;
  display: grid;
  grid-template-columns: 292px minmax(0, 1fr) 360px;
  background: var(--page-bg);
}

.left-oracle-rail {
  min-height: 100vh;
  border-right: 1px solid var(--line);
  background: var(--surface);
  display: flex;
  flex-direction: column;
}

.app-brand-lockup {
  display: grid;
  gap: 8px;
  padding: 22px 22px 16px;
  border-bottom: 1px solid var(--line);
}

.oracle-logo-mark {
  color: var(--oracle-red);
  font-weight: 800;
  letter-spacing: 0;
  font-size: 1.05rem;
}

.app-brand-lockup p,
.app-brand-lockup strong {
  margin: 0;
}

.app-brand-lockup p {
  color: var(--text-muted);
  font-size: 0.82rem;
}

.scene-rail {
  display: grid;
  gap: 6px;
  padding: 14px;
  overflow: auto;
}

.scene-nav-item {
  width: 100%;
  display: grid;
  grid-template-columns: 28px minmax(0, 1fr);
  gap: 10px;
  align-items: start;
  border: 1px solid transparent;
  background: transparent;
  color: var(--text-main);
  padding: 11px;
  text-align: left;
  cursor: pointer;
}

.scene-nav-item[aria-current="page"] {
  border-color: rgba(199, 70, 52, 0.34);
  background: rgb(var(--oj-palette-neutral-rgb-10, 244 242 240));
  box-shadow: inset 3px 0 0 var(--oracle-red);
}

.scene-nav-icon,
.jet-icon {
  color: currentColor;
  font-size: 1rem;
  line-height: 1;
}

.scene-nav-copy {
  display: grid;
  gap: 8px;
}

.scene-nav-label {
  font-weight: 700;
  line-height: 1.25;
}

.scene-nav-features,
.feature-chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.feature-chip {
  display: inline-flex;
  align-items: center;
  min-height: 22px;
  border: 1px solid rgba(199, 70, 52, 0.26);
  background: #fff7f4;
  color: #7b2f25;
  padding: 3px 7px;
  font-size: 0.72rem;
  font-weight: 700;
  line-height: 1.1;
}

.feature-chip--rail {
  background: #ffffff;
  color: var(--text-muted);
  border-color: var(--line);
  font-weight: 600;
}

.work-area {
  min-width: 0;
  display: grid;
  align-content: start;
  gap: 16px;
  padding: 18px;
}

.topbar {
  min-height: 72px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  border: 1px solid var(--line);
  background: var(--surface);
  padding: 16px;
}

.topbar h1 {
  margin: 6px 0 0;
  font-size: clamp(1.7rem, 2.2vw, 2.5rem);
  line-height: 1.05;
  letter-spacing: 0;
  color: var(--oracle-bark);
}

.topbar-actions {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  flex-wrap: wrap;
}

.utility-button,
.primary-button,
.secondary-button,
.dataset-action-button,
.oracle-panel-toggle {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  min-height: 38px;
  border: 1px solid var(--line);
  background: var(--surface);
  color: var(--text-main);
  padding: 9px 12px;
  cursor: pointer;
  font-weight: 700;
}

.utility-button--primary,
.primary-button {
  border-color: #a13b2d;
  background: var(--oracle-red);
  color: #ffffff;
}

.scene-body {
  display: grid;
  gap: 14px;
}

.scene-lead {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 18px;
  align-items: start;
  border: 1px solid var(--line);
  background: var(--surface);
  box-shadow: var(--shadow-sm);
  padding: 18px;
}

.scene-lead h2 {
  margin: 6px 0 10px;
  color: var(--oracle-bark);
  line-height: 1.2;
  font-size: 1.5rem;
}

.scene-lead p {
  margin: 0;
  color: var(--text-muted);
  line-height: 1.55;
}

.scene-lead__actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  justify-content: flex-end;
}

.runtime-card,
.metadata-panel article,
.right-oracle-panel {
  border: 1px solid var(--line);
  background: var(--surface);
  box-shadow: var(--shadow-sm);
}

.metadata-panel article {
  padding: 18px;
}

.metadata-panel h3,
.right-oracle-panel h2 {
  margin: 6px 0 10px;
  color: var(--oracle-bark);
  line-height: 1.2;
}

.metadata-panel p,
.dataset-card p,
.dataset-overlay__lede {
  margin: 0;
  color: var(--text-muted);
  line-height: 1.55;
}

.primary-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 16px;
}

.runtime-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.runtime-grid--compact {
  grid-template-columns: repeat(4, minmax(0, 1fr));
}

.runtime-card {
  padding: 14px;
}

.runtime-card__header,
.dataset-card__header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 10px;
}

.runtime-label,
.eyebrow,
.dataset-card__eyebrow {
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-size: 0.72rem;
  color: var(--oracle-red);
  font-weight: 700;
  margin: 0;
}

.runtime-value {
  margin: 0;
  word-break: break-word;
}

.action-log ul {
  margin: 10px 0 0;
  padding-left: 18px;
  color: var(--text-muted);
  line-height: 1.5;
}

.command-workbench,
.foundation-workbench,
.capability-workbench,
.operator-action-workbench,
.activity-strip {
  display: grid;
  gap: 14px;
}

.command-workbench {
  grid-template-columns: 152px minmax(230px, 1fr) minmax(240px, 0.9fr);
}

.foundation-workbench {
  grid-template-columns: minmax(250px, 0.9fr) minmax(260px, 1fr) minmax(220px, 0.8fr);
}

.capability-workbench,
.operator-action-workbench,
.activity-strip {
  grid-template-columns: minmax(260px, 0.9fr) minmax(260px, 1fr);
}

.queue-filter,
.decision-queue,
.schema-map,
.evidence-results,
.action-selector {
  display: grid;
  gap: 10px;
  align-content: start;
}

.chip-button,
.domain-object-card,
.schema-node,
.evidence-result,
.action-option {
  border: 1px solid var(--line);
  background: var(--surface);
  color: var(--text-main);
  padding: 12px;
  text-align: left;
  cursor: pointer;
}

.chip-button {
  text-align: center;
  font-weight: 800;
}

.chip-button--active,
.domain-object-card--active,
.schema-node--active,
.evidence-result--active,
.action-option--active {
  border-color: rgba(199, 70, 52, 0.38);
  background: #fff7f4;
  box-shadow: inset 3px 0 0 var(--oracle-red);
}

.domain-object-card,
.schema-node,
.evidence-result,
.action-option {
  display: grid;
  gap: 7px;
}

.domain-object-card span,
.evidence-result span {
  color: var(--oracle-red);
  font-size: 0.78rem;
  font-weight: 800;
}

.domain-object-card small,
.schema-node small,
.evidence-result small,
.action-option small {
  color: var(--text-muted);
  line-height: 1.4;
}

.decision-panel,
.schema-detail,
.lineage-panel,
.evidence-detail,
.action-review-panel,
.activity-strip article {
  border: 1px solid var(--line);
  background: var(--surface);
  box-shadow: var(--shadow-sm);
  padding: 16px;
}

.decision-panel h3,
.schema-detail h3,
.evidence-detail h3,
.action-review-panel h3 {
  margin: 6px 0 8px;
  color: var(--oracle-bark);
}

.decision-panel p,
.schema-detail p,
.evidence-detail p,
.action-review-panel p,
.activity-strip span {
  color: var(--text-muted);
  line-height: 1.5;
}

.field-chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin: 12px 0;
}

.field-chip-row span {
  border: 1px solid rgba(67, 124, 148, 0.26);
  background: rgba(67, 124, 148, 0.1);
  color: #25596d;
  padding: 4px 7px;
  font-size: 0.76rem;
  font-weight: 700;
}

.lineage-panel ol {
  margin: 8px 0 0;
  padding-left: 18px;
  color: var(--text-muted);
  line-height: 1.5;
}

.right-oracle-panel {
  min-height: 100vh;
  border-top: 0;
  border-bottom: 0;
  border-right: 0;
  padding: 16px;
  align-self: stretch;
  overflow: auto;
}

.right-oracle-panel--collapsed {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.oracle-panel-toggle {
  width: 100%;
  justify-content: flex-start;
  margin-bottom: 16px;
}

.oracle-panel-collapsed {
  color: var(--text-muted);
  margin: 0;
}

.oracle-evidence-list {
  display: grid;
  gap: 10px;
  margin: 14px 0 0;
}

.oracle-internals-section {
  border-top: 1px solid var(--line);
  padding-top: 14px;
  margin-top: 14px;
}

.oracle-internals-section:first-child {
  border-top: 0;
  padding-top: 0;
}

.oracle-internals-section h3 {
  margin: 4px 0 8px;
  color: var(--oracle-bark);
  font-size: 1rem;
  line-height: 1.25;
}

.oracle-internals-section p {
  margin: 0;
  color: var(--text-muted);
  line-height: 1.55;
}

.oracle-internals-badges {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin: 14px 0;
}

.oracle-feature-badge {
  display: inline-flex;
  align-items: center;
  min-height: 24px;
  border: 1px solid rgba(67, 124, 148, 0.28);
  background: rgba(67, 124, 148, 0.1);
  color: #25596d;
  padding: 4px 7px;
  font-size: 0.72rem;
  font-weight: 800;
  line-height: 1.1;
}

.oracle-feature-badge--red {
  border-color: rgba(199, 70, 52, 0.3);
  background: rgba(199, 70, 52, 0.1);
  color: #7b2f25;
}

.oracle-feature-badge--green {
  border-color: rgba(79, 125, 123, 0.3);
  background: rgba(79, 125, 123, 0.12);
  color: #2c5f5d;
}

.oracle-feature-badge--orange {
  border-color: rgba(170, 100, 59, 0.3);
  background: rgba(170, 100, 59, 0.12);
  color: #7a4728;
}

.oracle-feature-badge--purple {
  border-color: rgba(121, 96, 135, 0.3);
  background: rgba(121, 96, 135, 0.12);
  color: #594866;
}

.oracle-feature-badge--cyan {
  border-color: rgba(76, 130, 92, 0.3);
  background: rgba(76, 130, 92, 0.12);
  color: #346242;
}

.oracle-sql-block {
  margin: 14px 0;
  border: 1px solid var(--line);
  background: #1f1c1a;
  color: #f7f3ee;
}

.oracle-sql-block figcaption {
  border-bottom: 1px solid rgba(255, 255, 255, 0.14);
  padding: 8px 10px;
  color: #f4c7bc;
  font-size: 0.76rem;
  font-weight: 800;
}

.oracle-sql-block pre {
  margin: 0;
  padding: 12px;
  overflow: auto;
  font-size: 0.78rem;
  line-height: 1.45;
  white-space: pre-wrap;
}

.oracle-diagram-grid {
  display: grid;
  gap: 8px;
  margin: 14px 0;
}

.oracle-diagram-grid--flow {
  grid-template-columns: 1fr;
}

.oracle-diagram-box {
  border: 1px solid rgba(67, 124, 148, 0.32);
  border-left: 4px solid var(--oracle-red);
  background: rgb(var(--oj-palette-neutral-rgb-10, 244 242 240));
  padding: 10px;
}

.oracle-diagram-box strong,
.oracle-diagram-box span {
  display: block;
}

.oracle-diagram-box span {
  margin-top: 3px;
  color: var(--text-muted);
  font-size: 0.8rem;
}

.oracle-governance-callout {
  display: grid;
  grid-template-columns: 22px minmax(0, 1fr);
  gap: 10px;
  border: 1px solid rgba(199, 70, 52, 0.26);
  background: #fff7f4;
  color: #7b2f25;
  padding: 12px;
  margin: 14px 0;
}

.oracle-governance-callout p {
  margin: 4px 0 0;
  color: #7b2f25;
  line-height: 1.45;
}

.oracle-live-grid {
  display: grid;
  gap: 8px;
  margin: 10px 0 0;
}

.oracle-live-grid div {
  border-top: 1px solid var(--line);
  padding-top: 8px;
}

.oracle-live-grid dt {
  color: var(--text-muted);
  font-size: 0.76rem;
}

.oracle-live-grid dd {
  margin: 2px 0 0;
  word-break: break-word;
  font-weight: 700;
}

.oracle-evidence-list div {
  border-top: 1px solid var(--line);
  display: grid;
  gap: 4px;
  padding-top: 10px;
}

.oracle-evidence-list dt {
  color: var(--text-muted);
  font-size: 0.82rem;
}

.oracle-evidence-list dd {
  margin: 0;
  word-break: break-word;
}

.dataset-overlay {
  position: fixed;
  inset: 0;
  z-index: 30;
  display: grid;
  place-items: center;
}

.dataset-overlay__backdrop {
  position: absolute;
  inset: 0;
  border: 0;
  background: rgba(22, 21, 19, 0.42);
}

.dataset-overlay__panel {
  position: relative;
  width: min(980px, calc(100vw - 32px));
  max-height: calc(100vh - 32px);
  overflow: auto;
  padding: 24px;
  background: var(--surface);
  box-shadow: 0 24px 64px rgba(22, 21, 19, 0.18);
}

.dataset-overlay__header {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  align-items: start;
  margin-bottom: 18px;
}

.dataset-overlay__grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.dataset-card {
  border: 1px solid var(--line);
  background: var(--surface-alt);
  padding: 14px;
}

.dataset-card h3 {
  margin: 0 0 8px;
  font-size: 1rem;
  line-height: 1.35;
  color: var(--oracle-bark);
}

.dataset-action-button {
  width: 100%;
  margin-top: 12px;
  color: var(--oracle-red);
}

@media (max-width: 1180px) {
  .app-shell {
    grid-template-columns: 260px minmax(0, 1fr);
  }

  .right-oracle-panel {
    grid-column: 1 / -1;
    min-height: auto;
    border-left: 0;
    border-top: 1px solid var(--line);
  }
}

@media (max-width: 820px) {
  .app-shell,
  .metadata-panel,
  .runtime-grid,
  .runtime-grid--compact,
  .command-workbench,
  .foundation-workbench,
  .capability-workbench,
  .operator-action-workbench,
  .activity-strip,
  .dataset-overlay__grid,
  .scene-lead {
    grid-template-columns: 1fr;
  }

  .scene-lead__actions {
    justify-content: flex-start;
  }

  .left-oracle-rail {
    min-height: auto;
    border-right: 0;
    border-bottom: 1px solid var(--line);
  }

  .scene-rail {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .topbar,
  .dataset-overlay__header {
    align-items: stretch;
    flex-direction: column;
  }
}

@media (max-width: 560px) {
  .scene-rail {
    grid-template-columns: 1fr;
  }

  .work-area {
    padding: 12px;
  }

  .topbar-actions,
  .utility-button,
  .primary-button,
  .secondary-button {
    width: 100%;
  }
}
""",
    "database/migrations/changelog-root.xml": """<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd">

  <include file="changes/001-baseline.sql" relativeToChangelogFile="true"/>

</databaseChangeLog>
""",
    "database/migrations/changes/001-baseline.sql": """-- Replace with the baseline schema migration.
-- Keep table creation, constraints, and seed-independent setup here.
""",
    "database/sql/020_api_packages.sql": """-- Define PL/SQL package specs and bodies that implement the business API layer.
-- Keep package contracts stable and expose them through ORDS handlers.
""",
    "database/sql/030_ords.sql": """-- Enable the schema for ORDS and define modules, templates, handlers, and privileges here.
-- Prefer custom ORDS modules over table-level AutoREST for non-trivial flows.
""",
    "database/sql/040_security.sql": """-- Create roles, grants, policies, and audit configuration here.
-- Keep least-privilege boundaries explicit for app, ORDS, and admin identities.
""",
    "database/seed/050_demo_seed.sql": """-- Insert demo-only seed data here.
-- Keep customer onboarding logic separate from demo seed data.
""",
    "validation/acceptance-checklist.md": """# Acceptance Checklist

## External Readiness

- The generated app is production-credible for external users: protected destructive/admin routes, externalized secrets, fail-closed dependency behavior, and a meaningful `/healthz` readiness path.

## Multi-Agent Execution Evidence

- The role ledger records the opening specialist wave, owner type for each role, and exception reasons for any role kept local.

## Oracle Feature Evidence

- Oracle Database is the engine of the solution, Oracle AI Database 26ai capabilities are mapped to business outcomes, and Oracle Internals names the selected AI mode, feature, route/package, model/profile boundary, and data-egress caveat.

## Security Posture

- Least-privilege DB, ORDS, and app identities are documented. CORS, HTTPS, token handling, credential redaction, and operator-only dataset controls are covered.

## Live Runtime Proof

- The first app screen opens on an interactive operator workflow with a primary CTA, state change, and scene-aware Oracle evidence. `stack/compose.yml`, `.env.example`, guide screenshots, and validators match the final runtime.

## UI And Dataset Experience

- The app meets the premium Oracle Redwood / Oracle JET UI bar, uses Oracle Sans and known-rendering `oj-fwk-icon-*` glyphs, excludes Tailwind and non-JET app-chrome icon libraries, and exposes an Oracle logo/name lockup, left scene rail, top-right Oracle Internals plus Use Your Own Data controls, per-scene Oracle feature chips, and a right-side scene-aware Oracle Internals rail.
- Replaceable demo-data solutions include template download, validate preview, upload status, active dataset state, and demo restore.

## Remaining Risks

- Remaining risks are explicit and do not hide prototype-only or mock-backed runtime gaps.
""",
    "validation/launch-checklist.md": """# Launch Checklist

## Environment Readiness

## Service Startup

## Health Checks

## First Workflow Verification

## Guide Alignment
""",
    "validation/data-onboarding-checklist.md": """# Data Onboarding Checklist

## Source Contract

## Validate-Only Checks

## Upload Or Replace Checks

## Restore-Demo Checks

## Derived Artifact Rebuild

## Failure Handling
""",
    "validation/test-evidence.md": """# Test Evidence

## Red Tests

- Record tests that failed before the implementation change.
- Include the command, failure summary, and why the failure proves the missing behavior.

## Green Tests

- Record the same tests passing after implementation.
- Include the command, pass summary, and any runtime smoke evidence.

## A+ Grading Gate

- Run `python3 scripts/grade_livestack_bundle.py <solution-root>` from `$livestacks-orchestrator`.
- The bundle only passes when the grade is `A+` and the grading report says `Pass: yes`.

## Golden Parity

- Confirm `stack/compose.yml` and `stack/.env.example` match the capability-led runtime baseline.
- Confirm the app, ORDS, guide, screenshots, dataset-admin flow, and Oracle evidence work like the golden version before delivery.
""",
    "output/guide-screenshots/inventory.md": """# Guide Screenshot Inventory

Replace this placeholder inventory by running automated guide screenshot capture against the live app.
""",
    "output/guide-screenshots/inventory.json": """{
  "baseUrl": "",
  "capturedAt": "",
  "inventory": [],
  "failures": [
    "Replace this placeholder inventory by running automated guide screenshot capture against the live app."
  ]
}
""",
}


def write_file(path: Path, content: str, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        return
    path.write_text(content, encoding="utf-8")
    if path.suffix == ".sh":
        path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_dir", help="Parent directory where the solution folder should be created.")
    parser.add_argument("solution_slug", help="Folder name for the LiveStacks solution.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files in the target bundle.",
    )
    args = parser.parse_args()

    target_root = Path(args.output_dir).expanduser() / args.solution_slug
    target_root.mkdir(parents=True, exist_ok=True)

    for relative_path, content in FILES.items():
        write_file(target_root / relative_path, content, args.force)

    print(target_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
