FROM docker.io/library/nginx:stable-alpine

COPY deploy/vm/portal/nginx.conf /etc/nginx/templates/default.conf.template
COPY deploy/vm/portal/index.html /usr/share/nginx/html/index.html
COPY deploy/vm/portal/40-prepare-auth.sh /docker-entrypoint.d/40-prepare-auth.sh
RUN chmod 0755 /docker-entrypoint.d/40-prepare-auth.sh
