#!/usr/bin/env python3
"""Scaffold a canonical LiveStacks solution bundle."""

from __future__ import annotations

import argparse
from pathlib import Path


FILES = {
    "input/business-input.md": """# Business Input

Paste the raw user brief, workbook notes, PRD excerpts, or copied source material for this run in this file.

## Industry

## Category

## Pain Point

## Oracle Feature Mapping

## Implementation Notes

## Limitations / Risks

## Target Users

## Desired Demo Outcome

## Deployment Target

## Optional Services
""",
    "input/product-requirements.md": """# Product Requirements

## Source Mode

- Replace with `User-supplied PRD`, `Merged partial PRD`, or `No source PRD provided for this run`.

## Source Document

Replace this product requirements placeholder with the source PRD if one was provided for this run. Otherwise state that the build started from a brief and defer to `working-prd.md`.
""",
    "input/working-prd.md": """# Working PRD

This file becomes the build contract for the specialist wave. Create or update it before delegation. Every inferred item should be marked `Assumption:` until confirmed.

## Input Mode

- Replace with `PRD`, `Merge`, or `Bootstrap`.

## Source Inputs

## Program Context

Replace this working PRD placeholder with the synthesized build contract before delegation.

## Business Scenario

## Business Outcomes

## Personas

## Pain-Point Classification

## Core Workflow

## Story Architecture

## First Iteration Experience

## Oracle AI Database 26ai Protagonist Story

## AI Capability Mode

## Provider Boundary And Data Egress

## Oracle Feature Candidates

## Recommended Oracle Feature Set

## Rejected Features And Why

## Oracle Capability Mapping

## MVP Scope

## Non-Goals

## Feature Inventory

## Feature-To-Scene Mapping

## Data Contract

## Deployment And Runtime Assumptions

## Security And Trust Boundaries

## Redwood JET UI Quality Bar

## Non-Functional Requirements

## Acceptance Criteria

## Success Metrics

## Assumptions

## Open Questions
""",
    "input/assumptions.md": """# Assumptions

- Record only explicit assumptions made during orchestration.
- Remove assumptions that become confirmed requirements.
""",
    "input/template-provenance.json": """{
  "baseline": "neutral-golden-livestack-core",
  "baseline_version": "0.1.0",
  "overlay_source": "working-prd",
  "overlay_layers": [
    "industry_vocabulary",
    "pain_point_workflow",
    "story_scenes",
    "oracle_capability_map",
    "data_contract",
    "guide_runbook"
  ],
  "industry": "",
  "pain_point": "",
  "story_mode": "",
  "oracle_jet_redwood": true,
  "ords_first": true,
  "tailwind_allowed": false,
  "notes": [
    "Generated by livestacks-orchestrator from the neutral golden core contract.",
    "Keep stack/compose.yml and stack/.env.example aligned to the golden baseline assets.",
    "Replace empty values as soon as the working PRD is finalized.",
    "Use assets/template-overlays/industry-overlays.json as examples, not as raw templates."
  ]
}
""",
    "docs/problem-framing.md": """# Problem Framing

## Pain Point

## Users

## Business Outcomes

## Scope Boundaries
""",
    "docs/proposed-solution.md": """# Proposed Solution

## Summary

## Why Oracle Database Is The Engine

## Why This LiveStacks Shape Fits The Problem
""",
    "docs/architecture-decisions.md": """# Architecture Decisions

## Chosen Architecture

## Key Decisions

## Rejected Alternatives

## Chosen Implementation
""",
    "docs/data-design.md": """# Data Design

## Domain Model

## Oracle Feature Mapping

## ORDS Resource Plan

## Dataset Onboarding And State

## Oracle Evidence Map

## Migrations And Seed Strategy
""",
    "docs/ui-concept.md": """# UI Concept

Document the application in premium Oracle JET / Redwood terms. Use `$redwood-creator` as the app-UI lane source of truth when it is available. The UI contract is Oracle JET framework components, Redwood theme, JET typography/font variables backed by Oracle Sans, Oracle JET icon/glyph classes for app chrome, top-right masthead utility controls, and no Tailwind.

## Personas To Screens

## Story Mode

## First Scene Interaction

## Scene Sequence

## Primary CTA Path

## Screen Inventory

## Oracle Feature-To-Scene Map

## Dataset Admin Flow

## Upload Your Own Data Runtime Contract

## Oracle Internals Or Database X-Ray

## Oracle AI Evidence Fields

## Redwood JET Polish Bar

- Oracle JET framework components and Redwood theme import
- Oracle JET typography/font variables backed by Oracle Sans
- Oracle JET icon/glyph classes for sidebar navigation, titles, buttons, status, dataset actions, and Oracle Internals
- Top-right masthead controls for Oracle Internals and Upload Your Own Data
- No Tailwind config, `tailwindcss`, `@tailwind`, or utility-first replacement styling

## Critical Interactions

## Loading, Empty, And Error States
""",
    "docs/golden-core-overlays.md": """# Golden Core Overlays

Use this file to record how the neutral golden LiveStack core was adapted for this run.

## Baseline

- `baseline`: `neutral-golden-livestack-core`
- `baseline_version`: `0.1.0`
- `template_provenance`: `input/template-provenance.json`
- `compose_contract`: `stack/compose.yml` stays aligned to the golden baseline
- `env_contract`: `stack/.env.example` stays aligned to the golden baseline

## Industry Vocabulary

## Pain-Point Workflow

## Story Scenes

## Oracle Capability Map

## Data Contract

## Guide Runbook

## Residue Review

- No wrong-industry labels remain in customer-facing UI, guide, docs, or seed examples.
- `stack/compose.yml` and `stack/.env.example` remain core-owned and do not carry domain-specific overlays.
- No Newfold-specific language remains unless Newfold is the requested industry.
- No prior-template labels remain visible unless documented as internal compatibility.
- No Tailwind, `lucide-react`, emoji iconography, or non-JET icon packs are used for app chrome.
""",
    "docs/implementation-plan.md": """# Implementation Plan

## Milestones

## Dependencies

## Critical Path

## Validation Plan

## Open Issues
""",
    "docs/feature-inventory.md": """# Feature Inventory

## Primary Workflow Features

## Operator And Admin Features

## Oracle Evidence Features

## Deferred Or Out Of Scope
""",
    "docs/oracle-capability-map.md": """# Oracle Capability Map

## Protagonist Story

## Candidate Features Considered

## Chosen Feature Set

## Rejected Features And Why

## Capability To Business Mapping

## Required Oracle Dependencies

## AI Capability Mode

## Provider Boundary And Data Egress

## Security And Data-Egress Caveats

## Scene Evidence Mapping

## Oracle Evidence Surfaces

## Customer Rebuild Implications
""",
    "docs/risks-and-review.md": """# Risks And Review

## Challenged Assumptions

## Devil's Advocate Findings

## Revisions Made

## Remaining Risks
""",
    "docs/deployment-guide.md": """# Deployment Guide

## Prerequisites

## Environment Variables

## Build And Run

## Ollama Model Bootstrap

## Health Checks
""",
    "docs/customer-rebuild.md": """# Customer Rebuild Guide

## Dataset Admin Workflow

## Dataset Package Contract

## Replace Demo Data

## Adapt Integrations

## Restore Demo Baseline

## Validate In Customer Environment
""",
    "docs/runbook.md": """# Runbook

## Startup

## Ollama Model Bootstrap

## Operational Checks

## Troubleshooting

## Recovery Notes
""",
    "stack/compose.yml": """services:
  db:
    hostname: db
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: ${ORACLE_PWD:-change-me}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/oracle/oradata/.livestack_bootstrap_done ] && echo 'SELECT 1 FROM dual;' | sqlplus -L -s system/$${ORACLE_PWD:-change-me}@localhost:1521/FREEPDB1 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 40
      start_period: 180s
    networks:
      default:
        aliases:
          - db
    volumes:
      - db-data:/opt/oracle/oradata
      - ./db:/workspace/app/db:ro,z
      - ./scripts/bootstrap_db.sh:/opt/oracle/scripts/startup/20-bootstrap_db.sh:ro,z

  ords:
    hostname: ords
    image: container-registry.oracle.com/database/ords:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONN_STRING: db:1521/${DB_SERVICE:-FREEPDB1}
      DBHOST: db
      DBPORT: 1521
      DBSERVICENAME: ${DB_SERVICE:-FREEPDB1}
      ORDS_PUBLIC_URL: ${ORDS_PUBLIC_URL:-http://127.0.0.1:8181/ords/app}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
      ORACLE_PWD: ${ORACLE_PWD:-change-me}
    ports:
      - "8181:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ords/ >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 120s
    volumes:
      - ./ords-config:/etc/ords/config:Z,U
    networks:
      default:
        aliases:
          - ords

  ollama:
    hostname: ollama
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      default:
        aliases:
          - ollama
    volumes:
      - ollama-data:/root/.ollama

  app:
    hostname: app
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      db:
        condition: service_healthy
      ords:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      APP_ENV: ${APP_ENV:-development}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-}
      PORT: 3001
      ORDS_BASE_URL: ${ORDS_BASE_URL:-http://ords:8080/ords/app}
      DB_HOST: ${DB_HOST:-db}
      DB_SERVICE: ${DB_SERVICE:-FREEPDB1}
      DB_APP_USER: ${DB_APP_USER:-app_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-change-me}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama3.2}
      OLLAMA_EXTRA_MODELS: ${OLLAMA_EXTRA_MODELS:-gemma:2b}
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"require('http').get('http://127.0.0.1:3001/healthz', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "8505:3001"
    networks:
      default:
        aliases:
          - app

networks:
  default:

volumes:
  db-data:
  ollama-data:
""",
    "stack/Containerfile": """FROM node:20-bookworm

WORKDIR /workspace/app

COPY package.json ./
COPY frontend/package.json ./frontend/package.json
RUN npm install --include=dev \\
    && cd frontend \\
    && npm install --include=dev

COPY backend ./backend
COPY frontend ./frontend

RUN cd frontend && npm run build

EXPOSE 3001

CMD ["npm", "start"]
""",
    "stack/.env.example": """APP_ENV=development
ADMIN_TOKEN=
ORDS_BASE_URL=http://ords:8080/ords/app
ORDS_PUBLIC_URL=http://127.0.0.1:8181/ords/app
DB_HOST=db
DB_SERVICE=FREEPDB1
DB_APP_USER=app_user
DB_APP_PASSWORD=change-me
ORACLE_PWD=change-me
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_HOST_URL=http://127.0.0.1:11434
OLLAMA_MODEL=llama3.2
OLLAMA_EXTRA_MODELS=gemma:2b
OLLAMA_KEEP_ALIVE=30m
OLLAMA_WAIT_SECONDS=120
""",
    "stack/scripts/bootstrap_db.sh": """#!/bin/bash
set -euo pipefail

MARKER=/opt/oracle/oradata/.livestack_bootstrap_done
APP_ROOT=/workspace/app/db
APP_USER="${DB_APP_USER:-app_user}"
APP_PASSWORD="${DB_APP_PASSWORD:-change-me}"
ORACLE_PASSWORD="${ORACLE_PWD:-change-me}"

if [[ ! -d "$APP_ROOT" ]]; then
  echo "LiveStack database bootstrap directory is missing: $APP_ROOT" >&2
  exit 1
fi

sqlplus -L -s "system/${ORACLE_PASSWORD}@localhost:1521/FREEPDB1" <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM dba_users WHERE username = UPPER('${APP_USER}');
  IF l_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${APP_USER} IDENTIFIED BY "${APP_PASSWORD}" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER ${APP_USER} IDENTIFIED BY "${APP_PASSWORD}" ACCOUNT UNLOCK';
  END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TYPE, CREATE TRIGGER TO ${APP_USER};
GRANT CREATE JOB TO ${APP_USER};
GRANT UNLIMITED TABLESPACE TO ${APP_USER};
EXIT
SQL

for file in 001-baseline.sql 020_api_packages.sql 030_ords.sql 040_security.sql 050_demo_seed.sql; do
  if [[ -f "$APP_ROOT/$file" ]]; then
    echo "Applying $file"
    sqlplus -L -s "${APP_USER}/${APP_PASSWORD}@localhost:1521/FREEPDB1" @"$APP_ROOT/$file"
  fi
done

touch "$MARKER"
echo "LiveStack database bootstrap completed."
""",
    "stack/scripts/bootstrap_ollama_models.sh": """#!/bin/sh
set -eu

SCRIPT_DIR=$(
  CDPATH= cd -- "$(dirname -- "$0")" && pwd
)
STACK_DIR=$(
  CDPATH= cd -- "$SCRIPT_DIR/.." && pwd
)
ENV_FILE="$STACK_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi

OLLAMA_HOST_URL=${OLLAMA_HOST_URL:-http://127.0.0.1:11434}
OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}
OLLAMA_EXTRA_MODELS=${OLLAMA_EXTRA_MODELS:-gemma:2b}
OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-30m}
OLLAMA_WAIT_SECONDS=${OLLAMA_WAIT_SECONDS:-120}

wait_for_ollama() {
  start_time=$(date +%s)
  while :; do
    if curl -fsS "$OLLAMA_HOST_URL/api/tags" > /dev/null 2>&1; then
      return 0
    fi
    now=$(date +%s)
    elapsed=$((now - start_time))
    if [ "$elapsed" -ge "$OLLAMA_WAIT_SECONDS" ]; then
      printf '%s\\n' "Timed out waiting for Ollama at $OLLAMA_HOST_URL" >&2
      return 1
    fi
    sleep 2
  done
}

model_stream() {
  printf '%s\\n' "$OLLAMA_MODEL"
  printf '%s\\n' "$OLLAMA_EXTRA_MODELS" | tr ',' '\\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d'
}

pull_and_warm() {
  model="$1"
  printf '%s\\n' ">>> Pulling $model"
  curl -fsS \\
    --retry 5 \\
    --retry-all-errors \\
    --retry-delay 2 \\
    "$OLLAMA_HOST_URL/api/pull" \\
    -H "Content-Type: application/json" \\
    -d "{\\"model\\":\\"$model\\",\\"stream\\":false}" > /dev/null

  printf '%s\\n' ">>> Warming $model"
  curl -fsS \\
    --retry 5 \\
    --retry-all-errors \\
    --retry-delay 2 \\
    "$OLLAMA_HOST_URL/api/generate" \\
    -H "Content-Type: application/json" \\
    -d "{\\"model\\":\\"$model\\",\\"prompt\\":\\"ping\\",\\"stream\\":false,\\"keep_alive\\":\\"$OLLAMA_KEEP_ALIVE\\"}" > /dev/null
}

printf '%s\\n' ">>> Waiting for Ollama at $OLLAMA_HOST_URL"
wait_for_ollama

model_stream | awk '!seen[$0]++' | while IFS= read -r model; do
  pull_and_warm "$model"
done

printf '%s\\n' ">>> Available models:"
curl -fsS "$OLLAMA_HOST_URL/api/tags"
""",
    "stack/scripts/bootstrap_ollama_models.ps1": """[CmdletBinding()]
param(
    [string]$OllamaHostUrl = "",
    [string]$PrimaryModel = "",
    [string]$ExtraModels = "",
    [string]$KeepAlive = "",
    [int]$WaitSeconds = 0
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$stackDir = Split-Path -Parent $scriptDir
$envFile = Join-Path $stackDir ".env"

if (Test-Path $envFile) {
    foreach ($line in Get-Content $envFile) {
        $trimmed = $line.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
            continue
        }

        $parts = $line -split "=", 2
        if ($parts.Count -ne 2) {
            continue
        }

        $name = $parts[0].Trim()
        $value = $parts[1].Trim().Trim("'`"")
        if (-not [string]::IsNullOrWhiteSpace($name) -and -not (Test-Path "Env:$name")) {
            Set-Item -Path "Env:$name" -Value $value
        }
    }
}

if ([string]::IsNullOrWhiteSpace($OllamaHostUrl)) {
    $OllamaHostUrl = $env:OLLAMA_HOST_URL
}
if ([string]::IsNullOrWhiteSpace($OllamaHostUrl)) {
    $OllamaHostUrl = "http://127.0.0.1:11434"
}
if ([string]::IsNullOrWhiteSpace($PrimaryModel)) {
    $PrimaryModel = $env:OLLAMA_MODEL
}
if ([string]::IsNullOrWhiteSpace($PrimaryModel)) {
    $PrimaryModel = "llama3.2"
}
if ([string]::IsNullOrWhiteSpace($ExtraModels)) {
    $ExtraModels = $env:OLLAMA_EXTRA_MODELS
}
if ([string]::IsNullOrWhiteSpace($ExtraModels)) {
    $ExtraModels = "gemma:2b"
}
if ([string]::IsNullOrWhiteSpace($KeepAlive)) {
    $KeepAlive = $env:OLLAMA_KEEP_ALIVE
}
if ([string]::IsNullOrWhiteSpace($KeepAlive)) {
    $KeepAlive = "30m"
}
if ($WaitSeconds -le 0) {
    $WaitSeconds = 120
    if ($env:OLLAMA_WAIT_SECONDS -match "^\\d+$") {
        $WaitSeconds = [int]$env:OLLAMA_WAIT_SECONDS
    }
}

function Wait-ForOllama {
    $deadline = (Get-Date).AddSeconds($WaitSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri "$OllamaHostUrl/api/tags" -Method Get | Out-Null
            return
        } catch {
            Start-Sleep -Seconds 2
        }
    }

    throw "Timed out waiting for Ollama at $OllamaHostUrl"
}

function Pull-And-WarmModel([string]$Model) {
    Write-Host ">>> Pulling $Model"
    $pullBody = @{ model = $Model; stream = $false } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$OllamaHostUrl/api/pull" -Method Post -ContentType "application/json" -Body $pullBody | Out-Null

    Write-Host ">>> Warming $Model"
    $warmBody = @{ model = $Model; prompt = "ping"; stream = $false; keep_alive = $KeepAlive } | ConvertTo-Json -Compress
    Invoke-RestMethod -Uri "$OllamaHostUrl/api/generate" -Method Post -ContentType "application/json" -Body $warmBody | Out-Null
}

$models = @($PrimaryModel)
if (-not [string]::IsNullOrWhiteSpace($ExtraModels)) {
    $models += $ExtraModels.Split(",")
}
$models = $models |
    ForEach-Object { $_.Trim() } |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Select-Object -Unique

Write-Host ">>> Waiting for Ollama at $OllamaHostUrl"
Wait-ForOllama

foreach ($model in $models) {
    Pull-And-WarmModel -Model $model
}

Write-Host ">>> Available models:"
Invoke-RestMethod -Uri "$OllamaHostUrl/api/tags" -Method Get | ConvertTo-Json -Depth 6
""",
    "stack/package.json": """{
  "name": "livestacks-app-shell",
  "private": true,
  "version": "0.1.0",
  "description": "Default LiveStacks Oracle JET / Redwood operator workbench starter.",
  "main": "backend/server.js",
  "scripts": {
    "build": "cd frontend && npm run build",
    "start": "node backend/server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.21.2",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}
""",
    "stack/backend/server.js": """require("dotenv").config();

const fs = require("fs");
const path = require("path");
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");

const app = express();
const port = Number(process.env.PORT || 3001);
const frontendDist = path.join(__dirname, "../frontend/dist");
const hasBuiltFrontend = fs.existsSync(frontendDist);
const adminToken = process.env.ADMIN_TOKEN || "";

async function fetchOrds(pathname) {
  const baseUrl = process.env.ORDS_BASE_URL;
  if (!baseUrl) {
    return {
      status: "not_configured",
      message: "ORDS_BASE_URL is not configured yet.",
    };
  }

  const response = await fetch(`${baseUrl.replace(/\\/$/, "")}${pathname}`);
  const text = await response.text();
  let payload = text;
  try {
    payload = JSON.parse(text);
  } catch {
    // Preserve text payloads from ORDS diagnostics.
  }

  return {
    status: response.ok ? "ok" : "upstream_error",
    httpStatus: response.status,
    payload,
  };
}

async function fetchOllamaTags() {
  const baseUrl = process.env.OLLAMA_BASE_URL;
  if (!baseUrl) {
    return {
      status: "not_configured",
      message: "OLLAMA_BASE_URL is not configured.",
    };
  }

  const response = await fetch(`${baseUrl.replace(/\\/$/, "")}/api/tags`);
  const text = await response.text();
  let payload = text;
  try {
    payload = JSON.parse(text);
  } catch {
    // Preserve text payloads from Ollama diagnostics.
  }

  return {
    status: response.ok ? "ok" : "upstream_error",
    httpStatus: response.status,
    payload,
  };
}

async function runtimeStatus() {
  const ordsProbe = await fetchOrds("/read/v1/health").catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));
  const ollamaProbe = await fetchOllamaTags().catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));
  const components = {
    app: {
      status: hasBuiltFrontend ? "ok" : "frontend_missing",
      frontendBuilt: hasBuiltFrontend,
    },
    ords: ordsProbe,
    ollama: ollamaProbe,
  };
  const ready =
    components.app.status === "ok" &&
    components.ords.status === "ok" &&
    components.ollama.status === "ok";

  return {
    status: ready ? "ready" : "degraded",
    appEnv: process.env.APP_ENV || "development",
    ordsBaseUrl: process.env.ORDS_BASE_URL || "",
    ollamaBaseUrl: process.env.OLLAMA_BASE_URL || "",
    ollamaModel: process.env.OLLAMA_MODEL || "llama3.2",
    ollamaExtraModels: process.env.OLLAMA_EXTRA_MODELS || "gemma:2b",
    components,
  };
}

function requireAdmin(req, res, next) {
  if (!adminToken) {
    return res.status(503).json({
      status: "admin_token_missing",
      message: "Set ADMIN_TOKEN before enabling destructive dataset operations.",
    });
  }

  const authorization = req.get("authorization") || "";
  if (authorization !== `Bearer ${adminToken}`) {
    return res.status(401).json({
      status: "unauthorized",
      message: "Destructive dataset operations require Authorization: Bearer <ADMIN_TOKEN>.",
    });
  }

  return next();
}

app.use(helmet({ contentSecurityPolicy: false }));
app.use(
  cors({
    origin: ["http://localhost:5173", "http://localhost:3000", "http://localhost:8505"],
    credentials: true,
  })
);
app.use(morgan("dev"));
app.use(express.json({ limit: "10mb" }));

app.get("/healthz", async (req, res) => {
  const status = await runtimeStatus();
  res.status(status.status === "ready" ? 200 : 503).json(status);
});

app.get("/api/health", async (req, res) => {
  const status = await runtimeStatus();
  res.status(status.status === "ready" ? 200 : 503).json(status);
});

app.get("/api/oracle/evidence", async (req, res) => {
  const ordsProbe = await fetchOrds("/read/v1/health").catch((error) => ({
    status: "upstream_error",
    message: error.message,
  }));

  res.json({
    status: "starter_contract",
    message: "Replace this starter evidence response with solution-specific ORDS routes, PL/SQL packages, SQL, and Oracle AI feature usage before calling the bundle production-ready.",
    expectedSurface: "Oracle Internals or Database X-Ray",
    ai_capability_mode: "replace-with-vector-rag-dbms-vector-select-ai-or-documented-rejection",
    provider_boundary: "replace-with-local-ollama-external-provider-select-ai-profile-vector-credential-or-no-llm",
    data_egress_caveat: "replace-with-metadata-only-local-only-retrieved-chunks-results-to-provider-or-none",
    ordsBaseUrl: process.env.ORDS_BASE_URL || "",
    ordsProbe,
    evidence: [
      {
        label: "Route contract",
        value: "app -> ORDS -> PL/SQL package APIs -> Oracle Database",
      },
      {
        label: "First scene",
        value: "Primary operator CTA should update state and refresh this Oracle evidence payload.",
      },
      {
        label: "AI evidence",
        value: "Expose embedding model, vector index, Select AI action, provider boundary, and data-egress posture when selected.",
      },
    ],
  });
});

app.get("/api/import/dataset", (req, res) => {
  res.json({
    status: "starter_contract",
    source: "demo",
    activeDatasetStateTable: "APP_DATASET_STATE",
    adminBoundary: "Authorization: Bearer <ADMIN_TOKEN>",
    message: "Wire this endpoint to Oracle-backed dataset state for the solution.",
  });
});

app.get("/api/import/template", (req, res) => {
  res.json({
    status: "starter_contract",
    format: "zip",
    message: "Wire this endpoint to a generated template archive for supported customer-data files.",
  });
});

app.post("/api/import/validate", (req, res) => {
  res.json({
    status: "starter_contract",
    mode: "validate_only",
    message: "Wire this endpoint to ORDS-backed dataset validation before destructive upload.",
  });
});

app.post("/api/import/upload", requireAdmin, (req, res) => {
  res.status(202).json({
    status: "starter_contract",
    jobId: "replace-with-oracle-job-id",
    message: "Wire this endpoint to an Oracle-backed dataset replacement job.",
  });
});

app.post("/api/import/restore-demo/validate", (req, res) => {
  res.json({
    status: "starter_contract",
    mode: "validate_restore_demo",
    message: "Wire this endpoint to validate restore-demo impact before reset.",
  });
});

app.post("/api/import/restore-demo", requireAdmin, (req, res) => {
  res.status(202).json({
    status: "starter_contract",
    jobId: "replace-with-oracle-restore-job-id",
    message: "Wire this endpoint to a restore-demo job and active dataset state update.",
  });
});

app.get("/api/import/status/:jobId", (req, res) => {
  res.json({
    status: "starter_contract",
    jobId: req.params.jobId,
    message: "Wire this endpoint to the Oracle-backed import job ledger.",
  });
});

if (hasBuiltFrontend) {
  app.use(express.static(frontendDist));
}

app.get("*", (req, res, next) => {
  if (req.path.startsWith("/api")) {
    return next();
  }

  if (!hasBuiltFrontend) {
    return res.status(503).send(
      "Frontend build not found. Run `npm run build` inside `stack/frontend` before starting the production server."
    );
  }

  return res.sendFile(path.join(frontendDist, "index.html"));
});

app.listen(port, "0.0.0.0", () => {
  console.log("LiveStack Oracle JET / Redwood operator workbench listening on port", port);
});
""",
    "stack/frontend/package.json": """{
  "name": "livestacks-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --host 0.0.0.0 --port 4173"
  },
  "dependencies": {
    "@oracle/oraclejet": "^20.0.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.4",
    "vite": "^5.4.11"
  }
}
""",
    "stack/frontend/vite.config.js": """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    host: "0.0.0.0",
    port: 5173,
  },
});
""",
    "stack/frontend/index.html": """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>LiveStack Operator Workbench Starter</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
    "stack/frontend/src/main.jsx": """import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "@oracle/oraclejet/dist/css/redwood/oj-redwood-notag-min.css";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
""",
    "stack/frontend/src/App.jsx": """import { useEffect, useMemo, useState } from "react";

const fallbackStatus = {
  status: "checking",
  appEnv: "development",
  ordsBaseUrl: "",
  ollamaBaseUrl: "",
  ollamaModel: "llama3.2",
  ollamaExtraModels: "gemma:2b",
};

const scenes = [
  {
    id: "triage",
    label: "Triage",
    title: "Select the operator decision",
    primaryAction: "Start guided triage",
    outcome: "Triage state opened and Oracle evidence refreshed.",
    iconClass: "oj-fwk-icon-tree-document",
  },
  {
    id: "evidence",
    label: "Oracle Evidence",
    title: "Inspect the database path",
    primaryAction: "Refresh Oracle Internals",
    outcome: "Scene-aware X-Ray evidence requested from the app API.",
    iconClass: "oj-fwk-icon-database",
  },
  {
    id: "decision",
    label: "Decision",
    title: "Publish the recommended action",
    primaryAction: "Publish operator decision",
    outcome: "Decision state staged for the domain-specific ORDS write path.",
    iconClass: "oj-fwk-icon-checkmark",
  },
];

const datasetActions = [
  {
    eyebrow: "Template",
    title: "Download template ZIP",
    detail: "Offer the canonical import shape and identify source files versus regenerated Oracle artifacts.",
    iconClass: "oj-fwk-icon-tree-document",
  },
  {
    eyebrow: "Validate",
    title: "Preview upload before replace",
    detail: "Call the validate-only endpoint and show counts, warnings, rejects, and importability before destructive writes.",
    iconClass: "oj-fwk-icon-message-info",
  },
  {
    eyebrow: "Upload",
    title: "Run dataset replacement",
    detail: "Submit the replacement job, poll Oracle-backed job status, and refresh active dataset state.",
    iconClass: "oj-fwk-icon-arrowtail-e",
  },
  {
    eyebrow: "Restore",
    title: "Restore demo baseline",
    detail: "Provide a validate-first restore-demo path and keep the current dataset source visible.",
    iconClass: "oj-fwk-icon-clock",
  },
];

const qualityBar = [
  {
    label: "Premium Redwood",
    title: "Oracle JET / Redwood app lane",
    detail: "Use Oracle JET typography variables, Oracle Sans, documented Redwood colors, restrained rectangular geometry, and structural app surfaces.",
    iconClass: "oj-fwk-icon-view",
  },
  {
    label: "JET icons",
    title: "Control iconography",
    detail: "Use Oracle JET icons for navigation, actions, status, dataset controls, and Oracle Internals.",
    iconClass: "oj-fwk-icon-arrowtail-e",
  },
  {
    label: "Dataset admin",
    title: "Upload Your Own Data",
    detail: "Keep the persistent top-right masthead utility with validate, upload, job status, active state, and restore-demo.",
    iconClass: "oj-fwk-icon-arrowtail-e",
  },
];

function RuntimeCard({ label, value, iconClass }) {
  return (
    <article className="runtime-card">
      <div className="runtime-card__header">
        <span className={`oj-fwk-icon ${iconClass} jet-icon`} aria-hidden="true" />
        <p className="runtime-label">{label}</p>
      </div>
      <p className="runtime-value">{value}</p>
    </article>
  );
}

function HighlightCard({ label, title, detail, iconClass }) {
  return (
    <article className="highlight-card">
      <div className="highlight-card__header">
        <span className={`oj-fwk-icon ${iconClass} jet-icon`} aria-hidden="true" />
        <p className="highlight-card__eyebrow">{label}</p>
      </div>
      <h3>{title}</h3>
      <p>{detail}</p>
    </article>
  );
}

export default function App() {
  const [health, setHealth] = useState(fallbackStatus);
  const [activeSceneId, setActiveSceneId] = useState("triage");
  const [datasetOverlayOpen, setDatasetOverlayOpen] = useState(false);
  const [actionLog, setActionLog] = useState(["Workbench opened on the first operator decision."]);
  const [evidence, setEvidence] = useState({
    status: "pending",
    summary: "Oracle Internals will refresh when the primary operator action runs.",
    aiCapabilityMode: "pending",
    providerBoundary: "pending",
    dataEgressCaveat: "pending",
  });

  const activeScene = useMemo(
    () => scenes.find((scene) => scene.id === activeSceneId) || scenes[0],
    [activeSceneId]
  );

  useEffect(() => {
    let active = true;

    fetch("/api/health")
      .then((response) => response.json())
      .then((payload) => {
        if (active) {
          setHealth(payload);
        }
      })
      .catch(() => {
        if (active) {
          setHealth((current) => ({ ...current, status: "offline" }));
        }
      });

    return () => {
      active = false;
    };
  }, []);

  async function runPrimaryAction() {
    const stamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    setActionLog((items) => [`${stamp} - ${activeScene.outcome}`, ...items].slice(0, 5));

    try {
      const response = await fetch(`/api/oracle/evidence?scene=${activeScene.id}`);
      const payload = await response.json();
      setEvidence({
        status: payload.status || "ok",
        summary: payload.expectedSurface || "Oracle Internals",
        route: "/api/oracle/evidence",
        ordsBaseUrl: payload.ordsBaseUrl || "configure ORDS_BASE_URL",
        aiCapabilityMode: payload.ai_capability_mode || "replace with solution-specific AI mode",
        providerBoundary: payload.provider_boundary || "replace with provider boundary",
        dataEgressCaveat: payload.data_egress_caveat || "replace with data-egress caveat",
      });
    } catch {
      setEvidence({
        status: "offline",
        summary: "The app API is not reachable yet.",
        route: "/api/oracle/evidence",
        aiCapabilityMode: "unavailable",
        providerBoundary: "unavailable",
        dataEgressCaveat: "unavailable",
      });
    }
  }

  function stageDatasetAction(title) {
    const stamp = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    setActionLog((items) => [`${stamp} - Dataset action staged: ${title}`, ...items].slice(0, 5));
  }

  return (
    <main className="shell">
      <div className="utility-bar" aria-label="Application utilities">
        <button
          className="utility-button"
          type="button"
          onClick={() => document.getElementById("oracle-evidence-heading")?.scrollIntoView({ block: "center" })}
        >
          <span className="oj-fwk-icon oj-fwk-icon-database jet-icon" aria-hidden="true" />
          <span>Oracle Internals</span>
        </button>
        <button
          className="utility-button utility-button--primary"
          type="button"
          onClick={() => setDatasetOverlayOpen(true)}
        >
          <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
          <span>Upload Your Own Data</span>
        </button>
      </div>

      <section className="hero">
        <div className="hero-copy">
          <p className="eyebrow">Oracle JET Redwood Operator Workbench</p>
          <h1>Start on the operator decision, not a generic dashboard.</h1>
          <p className="lede">
            This LiveStack Operator Workbench Starter makes the first iteration interactive:
            a guided operator action, scene-aware Oracle Internals, JET iconography, and
            the persistent Upload Your Own Data dataset manager.
          </p>
          <p className="body-copy">
            Adapt the starter language to the domain, then wire each scene through
            app APIs that proxy ORDS routes backed by PL/SQL packages, SQL, and Oracle
            AI Database 26ai features.
          </p>

          <div className="scene-toolbar" aria-label="Workbench scenes">
            {scenes.map((scene) => (
              <button
                key={scene.id}
                className="scene-button"
                type="button"
                aria-pressed={scene.id === activeSceneId}
                onClick={() => setActiveSceneId(scene.id)}
              >
                <span className={`oj-fwk-icon ${scene.iconClass} jet-icon`} aria-hidden="true" />
                <span>{scene.label}</span>
              </button>
            ))}
          </div>

          <section className="decision-panel" aria-labelledby="first-scene-heading">
            <p className="highlight-card__eyebrow">first_scene_goal</p>
            <h2 id="first-scene-heading">{activeScene.title}</h2>
            <p>
              first_interaction: the operator uses the primary CTA, sees state change,
              and refreshes first_oracle_evidence for this scene.
            </p>
            <div className="primary-actions">
              <button className="primary-button" type="button" onClick={runPrimaryAction}>
                <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
                <span>{activeScene.primaryAction}</span>
              </button>
              <button
                className="secondary-button"
                type="button"
                onClick={() => setDatasetOverlayOpen(true)}
              >
                <span className="oj-fwk-icon oj-fwk-icon-arrowtail-e jet-icon" aria-hidden="true" />
                <span>Upload Your Own Data</span>
              </button>
            </div>
          </section>

          <div className="highlights-grid">
            {qualityBar.map((item) => (
              <HighlightCard key={item.title} {...item} />
            ))}
          </div>
        </div>

        <div className="hero-panel">
          <div className="hero-status">
            <span className="hero-status__label">Runtime status</span>
            <strong>{health.status}</strong>
          </div>
          <div className="runtime-grid">
            <RuntimeCard label="APP_ENV" value={health.appEnv || "development"} iconClass="oj-fwk-icon-grid" />
            <RuntimeCard label="ORDS" value={health.ordsBaseUrl || "configure ORDS_BASE_URL"} iconClass="oj-fwk-icon-database" />
            <RuntimeCard label="OLLAMA" value={health.ollamaBaseUrl || "configure OLLAMA_BASE_URL"} iconClass="oj-fwk-icon-message-info" />
            <RuntimeCard label="PRIMARY MODEL" value={health.ollamaModel || "llama3.2"} iconClass="oj-fwk-icon-view" />
          </div>

          <section className="oracle-evidence" aria-labelledby="oracle-evidence-heading">
            <p className="callout-label">Oracle Internals</p>
            <h2 id="oracle-evidence-heading">Scene-aware X-Ray</h2>
            <dl>
              <div>
                <dt>Status</dt>
                <dd>{evidence.status}</dd>
              </div>
              <div>
                <dt>Route</dt>
                <dd>{evidence.route || "waiting for first action"}</dd>
              </div>
              <div>
                <dt>Evidence</dt>
                <dd>{evidence.summary}</dd>
              </div>
              <div>
                <dt>AI mode</dt>
                <dd>{evidence.aiCapabilityMode}</dd>
              </div>
              <div>
                <dt>Boundary</dt>
                <dd>{evidence.providerBoundary}</dd>
              </div>
              <div>
                <dt>Data egress</dt>
                <dd>{evidence.dataEgressCaveat}</dd>
              </div>
            </dl>
          </section>

          <section className="action-log" aria-live="polite">
            <p className="callout-label">Action log</p>
            <ul>
              {actionLog.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>
        </div>
      </section>

      {datasetOverlayOpen ? (
        <div className="dataset-overlay" role="dialog" aria-modal="true" aria-labelledby="dataset-overlay-title">
          <button
            className="dataset-overlay__backdrop"
            type="button"
            aria-label="Close dataset admin overlay"
            onClick={() => setDatasetOverlayOpen(false)}
          />
          <section className="dataset-overlay__panel">
            <div className="dataset-overlay__header">
              <div>
                <p className="eyebrow">Operator Dataset Admin</p>
                <h2 id="dataset-overlay-title">Upload Your Own Data</h2>
                <p className="dataset-overlay__lede">
                  Use this first-iteration control surface for template download,
                  validate-only preview, upload or replace, Oracle-backed job status,
                  active dataset state, and restore-demo.
                </p>
              </div>
              <button
                className="dataset-overlay__close"
                type="button"
                onClick={() => setDatasetOverlayOpen(false)}
              >
                Close
              </button>
            </div>

            <div className="dataset-overlay__grid">
              {datasetActions.map((item) => (
                <article key={item.title} className="dataset-card">
                  <div className="dataset-card__header">
                    <span className={`oj-fwk-icon ${item.iconClass} jet-icon`} aria-hidden="true" />
                    <p className="dataset-card__eyebrow">{item.eyebrow}</p>
                  </div>
                  <h3>{item.title}</h3>
                  <p>{item.detail}</p>
                  <button
                    className="dataset-action-button"
                    type="button"
                    onClick={() => stageDatasetAction(item.title)}
                  >
                    Stage action
                  </button>
                </article>
              ))}
            </div>
          </section>
        </div>
      ) : null}
    </main>
  );
}
""",
    "stack/frontend/src/styles.css": """:root {
  color-scheme: light;
  --oracle-red: #c74634;
  --oracle-bark: #312d2a;
  --surface: var(--oj-core-bg-color-content, #ffffff);
  --surface-alt: rgb(var(--oj-palette-neutral-rgb-10, 244 242 240));
  --line: var(--oj-core-divider-color, rgba(49, 45, 42, 0.14));
  --text-main: var(--oj-core-text-color-primary, #161513);
  --text-muted: var(--oj-core-text-color-secondary, #4f4a46);
  --shadow-sm: 0 8px 20px rgba(22, 21, 19, 0.06);
  font-family: var(--oj-html-font-family, "Oracle Sans", "Segoe UI", sans-serif);
  color: var(--text-main);
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100vh;
}

body {
  background: linear-gradient(
    180deg,
    rgb(var(--oj-palette-neutral-rgb-0, 255 255 255)) 0%,
    rgb(var(--oj-palette-neutral-rgb-10, 244 242 240)) 100%
  );
  color: var(--text-main);
  /* Oracle JET Redwood theme supplies --oj-html-font-family; Oracle Sans remains the required fallback. */
  font-family: var(--oj-html-font-family, "Oracle Sans", "Segoe UI", sans-serif);
}

#root {
  min-height: 100vh;
}

.shell {
  min-height: 100vh;
  padding: 84px 24px 32px;
  position: relative;
}

.utility-bar {
  position: fixed;
  top: 18px;
  right: 24px;
  z-index: 20;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
}

.utility-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  min-height: 38px;
  padding: 9px 12px;
  border: 1px solid var(--line);
  background: var(--surface);
  color: var(--text-main);
  box-shadow: var(--shadow-sm);
  cursor: pointer;
  font: inherit;
  font-weight: 700;
}

.utility-button--primary {
  border-color: #a13b2d;
  background: var(--oracle-red);
  color: #ffffff;
}

.hero {
  display: grid;
  grid-template-columns: minmax(0, 1.28fr) minmax(320px, 0.78fr);
  gap: 16px;
  max-width: 1240px;
  margin: 0 auto;
}

.hero-copy,
.hero-panel {
  background: var(--surface);
  border: 1px solid var(--line);
  box-shadow: var(--shadow-sm);
}

.hero-copy {
  padding: 28px;
  border-top: 4px solid var(--oracle-red);
}

.hero-panel {
  padding: 24px;
  align-self: start;
}

.eyebrow,
.runtime-label,
.callout-label,
.highlight-card__eyebrow,
.dataset-card__eyebrow,
.hero-status__label {
  text-transform: uppercase;
  letter-spacing: 0.14em;
  font-size: 0.72rem;
  color: var(--oracle-red);
  font-weight: 700;
  margin: 0;
}

h1 {
  margin: 10px 0 14px;
  font-size: clamp(2.2rem, 3.8vw, 4.2rem);
  line-height: 1;
  letter-spacing: 0;
  color: var(--oracle-bark);
}

h2 {
  margin: 0;
  color: var(--oracle-bark);
  line-height: 1.2;
}

.lede {
  font-size: 1.05rem;
  line-height: 1.65;
  margin: 0 0 12px;
}

.body-copy {
  margin: 0;
  color: var(--text-muted);
  line-height: 1.65;
  max-width: 58ch;
}

.highlights-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
  margin-top: 22px;
}

.scene-toolbar {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin: 22px 0 14px;
}

.scene-button,
.primary-button,
.secondary-button,
.dataset-action-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  border: 1px solid var(--line);
  background: var(--surface);
  color: var(--text-main);
  min-height: 40px;
  padding: 10px 13px;
  cursor: pointer;
  font: inherit;
}

.scene-button[aria-pressed="true"] {
  border-color: var(--oracle-red);
  color: var(--oracle-red);
  box-shadow: inset 0 -2px 0 var(--oracle-red);
}

.decision-panel,
.oracle-evidence,
.action-log {
  border: 1px solid var(--line);
  background: var(--surface-alt);
  padding: 16px;
}

.decision-panel {
  display: grid;
  gap: 12px;
  margin-top: 14px;
}

.decision-panel p {
  margin: 0;
  line-height: 1.55;
  color: var(--text-muted);
}

.primary-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.primary-button {
  border-color: #a13b2d;
  background: var(--oracle-red);
  color: #ffffff;
  font-weight: 700;
}

.secondary-button {
  background: var(--surface);
}

.highlight-card,
.runtime-card,
.dataset-card {
  border: 1px solid var(--line);
  background: var(--surface-alt);
  padding: 14px;
}

.highlight-card__header,
.runtime-card__header,
.dataset-card__header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 10px;
}

.highlight-card h3,
.dataset-card h3 {
  margin: 0 0 8px;
  font-size: 1rem;
  line-height: 1.35;
  color: var(--oracle-bark);
}

.highlight-card p,
.dataset-card p {
  margin: 0;
  line-height: 1.55;
  color: var(--text-muted);
}

.jet-icon {
  color: currentColor;
  font-size: 1rem;
  line-height: 1;
}

.hero-status {
  display: grid;
  gap: 4px;
  padding-bottom: 14px;
  margin-bottom: 16px;
  border-bottom: 1px solid var(--line);
}

.hero-status strong {
  font-size: 1.12rem;
  line-height: 1.2;
  color: var(--oracle-bark);
}

.runtime-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.runtime-label {
  color: var(--text-muted);
}

.runtime-value {
  margin: 0;
  font-size: 0.98rem;
  line-height: 1.5;
  word-break: break-word;
}

.callout {
  margin-top: 18px;
  padding: 16px 0 0;
  border-top: 1px solid var(--line);
}

.callout p {
  margin: 0;
}

.oracle-evidence {
  margin-top: 18px;
}

.oracle-evidence h2 {
  margin: 6px 0 12px;
  font-size: 1.12rem;
}

.oracle-evidence dl {
  display: grid;
  gap: 10px;
  margin: 0;
}

.oracle-evidence div {
  display: grid;
  grid-template-columns: 86px minmax(0, 1fr);
  gap: 10px;
  border-top: 1px solid var(--line);
  padding-top: 10px;
}

.oracle-evidence dt {
  color: var(--text-muted);
  font-size: 0.82rem;
}

.oracle-evidence dd {
  margin: 0;
  word-break: break-word;
}

.action-log {
  margin-top: 12px;
}

.action-log ul {
  margin: 10px 0 0;
  padding-left: 18px;
  color: var(--text-muted);
  line-height: 1.5;
}

.dataset-overlay {
  position: fixed;
  inset: 0;
  z-index: 30;
  display: grid;
  place-items: center;
}

.dataset-overlay__backdrop {
  position: absolute;
  inset: 0;
  border: 0;
  background: rgba(22, 21, 19, 0.42);
}

.dataset-overlay__panel {
  position: relative;
  width: min(980px, calc(100vw - 32px));
  padding: 24px;
  background: var(--surface);
  box-shadow: 0 24px 64px rgba(22, 21, 19, 0.18);
}

.dataset-overlay__header {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  align-items: start;
  margin-bottom: 18px;
}

.dataset-overlay__lede {
  margin: 12px 0 0;
  max-width: 60ch;
  line-height: 1.6;
  color: var(--text-muted);
}

.dataset-overlay__close {
  border: 1px solid var(--line);
  padding: 10px 14px;
  background: var(--surface);
  cursor: pointer;
  color: var(--text-main);
}

.dataset-overlay__grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.dataset-action-button {
  margin-top: 12px;
  width: 100%;
  color: var(--oracle-red);
  font-weight: 700;
}

@media (max-width: 920px) {
  .hero,
  .highlights-grid,
  .runtime-grid,
  .dataset-overlay__grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 640px) {
  .shell {
    padding: 112px 16px 24px;
  }

  .hero-copy,
  .hero-panel,
  .dataset-overlay__panel {
    padding: 20px;
  }

  .utility-bar {
    top: 12px;
    left: 16px;
    right: 16px;
    align-items: stretch;
    flex-direction: column;
  }

  .utility-button {
    width: 100%;
  }

  .dataset-overlay__header {
    flex-direction: column;
  }
}
""",
    "database/migrations/changelog-root.xml": """<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.20.xsd">

  <include file="changes/001-baseline.sql" relativeToChangelogFile="true"/>

</databaseChangeLog>
""",
    "database/migrations/changes/001-baseline.sql": """-- Replace with the baseline schema migration.
-- Keep table creation, constraints, and seed-independent setup here.
""",
    "database/sql/020_api_packages.sql": """-- Define PL/SQL package specs and bodies that implement the business API layer.
-- Keep package contracts stable and expose them through ORDS handlers.
""",
    "database/sql/030_ords.sql": """-- Enable the schema for ORDS and define modules, templates, handlers, and privileges here.
-- Prefer custom ORDS modules over table-level AutoREST for non-trivial flows.
""",
    "database/sql/040_security.sql": """-- Create roles, grants, policies, and audit configuration here.
-- Keep least-privilege boundaries explicit for app, ORDS, and admin identities.
""",
    "database/seed/050_demo_seed.sql": """-- Insert demo-only seed data here.
-- Keep customer onboarding logic separate from demo seed data.
""",
    "validation/acceptance-checklist.md": """# Acceptance Checklist

## External Readiness

- The generated app is production-credible for external users: protected destructive/admin routes, externalized secrets, fail-closed dependency behavior, and a meaningful `/healthz` readiness path.

## Multi-Agent Execution Evidence

- The role ledger records the opening specialist wave, owner type for each role, and exception reasons for any role kept local.

## Oracle Feature Evidence

- Oracle Database is the engine of the solution, Oracle AI Database 26ai capabilities are mapped to business outcomes, and Oracle Internals names the selected AI mode, feature, route/package, model/profile boundary, and data-egress caveat.

## Security Posture

- Least-privilege DB, ORDS, and app identities are documented. CORS, HTTPS, token handling, credential redaction, and operator-only dataset controls are covered.

## Live Runtime Proof

- The first app screen opens on an interactive operator workflow with a primary CTA, state change, and scene-aware Oracle evidence. `stack/compose.yml`, `.env.example`, guide screenshots, and validators match the final runtime.

## UI And Dataset Experience

- The app meets the premium Oracle Redwood / Oracle JET UI bar, uses Oracle Sans and known-rendering `oj-fwk-icon-*` glyphs, excludes Tailwind and non-JET app-chrome icon libraries, and exposes top-right Oracle Internals plus Upload Your Own Data controls.
- Replaceable demo-data solutions include template download, validate preview, upload status, active dataset state, and demo restore.

## Remaining Risks

- Remaining risks are explicit and do not hide prototype-only or mock-backed runtime gaps.
""",
    "validation/launch-checklist.md": """# Launch Checklist

## Environment Readiness

## Service Startup

## Health Checks

## First Workflow Verification

## Guide Alignment
""",
    "validation/data-onboarding-checklist.md": """# Data Onboarding Checklist

## Source Contract

## Validate-Only Checks

## Upload Or Replace Checks

## Restore-Demo Checks

## Derived Artifact Rebuild

## Failure Handling
""",
    "validation/test-evidence.md": """# Test Evidence

## Red Tests

- Record tests that failed before the implementation change.
- Include the command, failure summary, and why the failure proves the missing behavior.

## Green Tests

- Record the same tests passing after implementation.
- Include the command, pass summary, and any runtime smoke evidence.

## A+ Grading Gate

- Run `python3 scripts/grade_livestack_bundle.py <solution-root>` from `$livestacks-orchestrator`.
- The bundle only passes when the grade is `A+` and the grading report says `Pass: yes`.

## Golden Parity

- Confirm `stack/compose.yml` and `stack/.env.example` match the neutral golden LiveStack baseline.
- Confirm the app, ORDS, guide, screenshots, dataset-admin flow, and Oracle evidence work like the golden version before delivery.
""",
    "output/guide-screenshots/inventory.md": """# Guide Screenshot Inventory

Replace this placeholder inventory by running automated guide screenshot capture against the live app.
""",
    "output/guide-screenshots/inventory.json": """{
  "baseUrl": "",
  "capturedAt": "",
  "inventory": [],
  "failures": [
    "Replace this placeholder inventory by running automated guide screenshot capture against the live app."
  ]
}
""",
}


def write_file(path: Path, content: str, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        return
    path.write_text(content, encoding="utf-8")
    if path.suffix == ".sh":
        path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_dir", help="Parent directory where the solution folder should be created.")
    parser.add_argument("solution_slug", help="Folder name for the LiveStacks solution.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files in the target bundle.",
    )
    args = parser.parse_args()

    target_root = Path(args.output_dir).expanduser() / args.solution_slug
    target_root.mkdir(parents=True, exist_ok=True)

    for relative_path, content in FILES.items():
        write_file(target_root / relative_path, content, args.force)

    print(target_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
